<a href="https://colab.research.google.com/github/AbnerJSV/THE_CORE_Trabajos_iA/blob/main/Telemetria_Videojuegos/TelemetriaDeVideojuegos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
# Importar la librería pandas para manipulación de datos
import pandas as pd

# Cargar el archivo CSV 'videojuegos_online_telemetria.csv' en un DataFrame de pandas.
# Consejo: Siempre es buena práctica verificar el encoding si el archivo CSV no se carga correctamente.
# Por ejemplo: pd.read_csv('archivo.csv', encoding='latin1')
df = pd.read_csv('videojuegos_online_telemetria.csv')

# Mostrar las primeras 5 filas del DataFrame para una primera inspección de los datos.
# Esto ayuda a entender la estructura y el tipo de datos presentes.
# Consejo: Después de cargar los datos, considera usar `df.info()` para ver los tipos de datos y los valores no nulos, y `df.describe()` para estadísticas descriptivas de columnas numéricas.
print('Primeras 5 filas del DataFrame:')
print(df.head())

Primeras 5 filas del DataFrame:
  PlayerID   Age Region Platform PreferredGenre  SessionsPerWeek  \
0    P0001  22.0  LATAM       PC            RPG                3
1    P0002  21.0     EU       PC        Shooter                7
2    P0003  40.0  LATAM   Mobile        Shooter                3
3    P0004  37.0    NaN       PC        Shooter                0
4    P0005  28.0     EU  Console        Shooter                3

   AvgSessionMinutes  DaysSinceLastLogin  PlayerLevel  MatchesPlayedLast30D  \
0               87.0                  11           59                    14
1              113.0                   0           45                    24
2               67.0                   3           68                    27
3               48.0                   9           40                    39
4               90.0                  15           51                    15

   WinRate  InGamePurchase  FriendsInGame  UsesVoiceChat  \
0    0.481            7.38            3.0              1
1    0.475           11.56            8.0              1
2    0.341            0.42            6.0              1
3    0.225            8.83            NaN              1
4    0.454           23.86            0.0              0

   AchievementsUnlocked  ReportsReceivedLast30D  Churn30D
0                    17                       0         0
1                    21                       2         0
2                    26                       1         0
3                    41                       2         0
4                    35                       1         1

In [33]:
# Contar el número de valores duplicados en la columna 'PlayerID'.
# 'duplicated()' devuelve una serie booleana indicando si cada fila es un duplicado.
# Por defecto, `keep='first'` marca como True las ocurrencias duplicadas excepto la primera.
# `.sum()` cuenta cuántos valores True hay, es decir, el número de duplicados.
num_duplicates = df['PlayerID'].duplicated().sum()

# Mostrar el resultado del conteo de duplicados.
if num_duplicates > 0:
    print(f"Se encontraron {num_duplicates} valores duplicados en la columna 'PlayerID'.")
    print("Las filas duplicadas (manteniendo la primera aparición) son:")
    # Mostrar solo las filas que son duplicados (excluyendo la primera ocurrencia).
    # Consejo: Es importante revisar estas filas para entender la naturaleza de los duplicados antes de eliminarlos.
    display(df[df['PlayerID'].duplicated(keep='first')])
else:
    print("No se encontraron valores duplicados en la columna 'PlayerID'.")

Se encontraron 8 valores duplicados en la columna 'PlayerID'.
Las filas duplicadas (manteniendo la primera aparición) son:

,PlayerID,Age,Region,Platform,PreferredGenre,SessionsPerWeek,AvgSessionMinutes,DaysSinceLastLogin,PlayerLevel,MatchesPlayedLast30D,WinRate,InGamePurchase,FriendsInGame,UsesVoiceChat,AchievementsUnlocked,ReportsReceivedLast30D,Churn30D
550,P0196,31.0,LATAM,PC,RPG,4,127.0,2,56,33,0.545,20.40,0.0,1,28,0,0
551,P0080,37.0,NaN,pc,RPG,1,89.0,3,52,23,0.496,0.90,5.0,1,0,0,0
552,P0481,40.0,EU,PC,Sports,2,111.0,6,15,30,0.357,0.50,13.0,1,22,2,1
553,P0110,20.0,EU,Console,RPG,1,97.0,11,76,12,0.469,26.12,1.0,0,19,2,0
554,P0523,27.0,EU,PC,Shooter,3,91.0,7,27,3,0.513,1.60,15.0,1,27,4,0
555,P0533,28.0,EU,pc,Battle Royale,4,87.0,5,6,0,0.528,0.18,4.0,0,10,0,0
556,P0085,30.0,LATAM,PC,RPG,4,33.0,10,46,20,0.736,5.09,0.0,1,46,3,0
557,P0369,29.0,EU,PC,Sports,2,96.0,0,23,34,0.332,25.64,12.0,0,36,0,1

In [34]:
# Mostrar todas las filas que tienen valores duplicados en la columna 'PlayerID'.
# `keep=False` marca como True todas las ocurrencias de los duplicados, incluyendo la primera.
# Esto permite ver el grupo completo de filas que comparten un 'PlayerID' duplicado.
duplicated_rows = df[df['PlayerID'].duplicated(keep=False)]

# Verificar si se encontraron filas duplicadas y mostrarlas.
if not duplicated_rows.empty:
    print("Todas las filas con 'PlayerID' duplicados son:")
    # Consejo: Analizar estas filas es crucial para decidir cómo manejar los duplicados (ej. ¿cuál es la fila 'correcta' si hay inconsistencias?).
    display(duplicated_rows)
else:
    print("No se encontraron valores duplicados en la columna 'PlayerID'.")

Todas las filas con 'PlayerID' duplicados son:

,PlayerID,Age,Region,Platform,PreferredGenre,SessionsPerWeek,AvgSessionMinutes,DaysSinceLastLogin,PlayerLevel,MatchesPlayedLast30D,WinRate,InGamePurchase,FriendsInGame,UsesVoiceChat,AchievementsUnlocked,ReportsReceivedLast30D,Churn30D
79,P0080,37.0,NaN,pc,RPG,1,89.0,3,52,23,0.496,0.90,5.0,1,0,0,0
84,P0085,30.0,LATAM,PC,RPG,4,33.0,10,46,20,0.736,5.09,0.0,1,46,3,0
109,P0110,20.0,EU,Console,RPG,1,97.0,11,76,12,0.469,26.12,1.0,0,19,2,0
195,P0196,31.0,LATAM,PC,RPG,4,127.0,2,56,33,0.545,20.40,0.0,1,28,0,0
368,P0369,29.0,EU,PC,Sports,2,96.0,0,23,34,0.332,25.64,12.0,0,36,0,1
480,P0481,40.0,EU,PC,Sports,2,111.0,6,15,30,0.357,0.50,13.0,1,22,2,1
522,P0523,27.0,EU,PC,Shooter,3,91.0,7,27,3,0.513,1.60,15.0,1,27,4,0
532,P0533,28.0,EU,pc,Battle Royale,4,87.0,5,6,0,0.528,0.18,4.0,0,10,0,0
550,P0196,31.0,LATAM,PC,RPG,4,127.0,2,56,33,0.545,20.40,0.0,1,28,0,0
551,P0080,37.0,NaN,pc,RPG,1,89.0,3,52,23,0.496,0.90,5.0,1,0,0,0
552,P0481,40.0,EU,PC,Sports,2,111.0,6,15,30,0.357,0.50,13.0,1,22,2,1
553,P0110,20.0,EU,Console,RPG,1,97.0,11,76,12,0.469,26.12,1.0,0,19,2,0
554,P0523,27.0,EU,PC,Shooter,3,91.0,7,27,3,0.513,1.60,15.0,1,27,4,0
555,P0533,28.0,EU,pc,Battle Royale,4,87.0,5,6,0,0.528,0.18,4.0,0,10,0,0
556,P0085,30.0,LATAM,PC,RPG,4,33.0,10,46,20,0.736,5.09,0.0,1,46,3,0
557,P0369,29.0,EU,PC,Sports,2,96.0,0,23,34,0.332,25.64,12.0,0,36,0,1

In [35]:
# Eliminar filas duplicadas basándose únicamente en la columna 'PlayerID'.
# `subset=['PlayerID']` especifica que la búsqueda de duplicados se haga solo en esta columna.
# `keep='first'` asegura que la primera ocurrencia de cada 'PlayerID' se mantenga y las siguientes se eliminen.
df_cleaned = df.drop_duplicates(subset=['PlayerID'], keep='first')

# Mostrar el número de filas antes y después de la eliminación para verificar la operación.
print(f"Filas antes de eliminar duplicados: {df.shape[0]}")
print(f"Filas después de eliminar duplicados: {df_cleaned.shape[0]}")

# Actualizar el DataFrame original `df` con el DataFrame limpio `df_cleaned`.
# Se utiliza `.copy()` para asegurar que `df` sea una copia independiente y evitar `SettingWithCopyWarning` en futuras operaciones.
df = df_cleaned.copy()

# Verificar si aún existen duplicados en 'PlayerID' para confirmar que la eliminación fue exitosa.
num_remaining_duplicates = df['PlayerID'].duplicated().sum()
if num_remaining_duplicates == 0:
    print("\nSe han eliminado todos los duplicados en la columna 'PlayerID'.")
else:
    print(f"\nTodavía quedan {num_remaining_duplicates} duplicados en 'PlayerID'.")
# Consejo: Siempre verifica el éxito de la operación de limpieza de datos.

Filas antes de eliminar duplicados: 558
Filas después de eliminar duplicados: 550

Se han eliminado todos los duplicados en la columna 'PlayerID'.

### Manejo de valores faltantes en la columna 'Age'

Vamos a calcular la mediana de la columna 'Age' y usarla para rellenar los valores faltantes (NaN) en esta columna.

In [36]:
# Calcular la mediana de la columna 'Age'. La mediana es robusta a valores atípicos (outliers).
median_age = df['Age'].median()
print(f"Mediana de la columna 'Age': {median_age}")

# Rellenar los valores faltantes (NaN) en la columna 'Age' con la mediana calculada.
# `df.loc[:, 'Age']` se usa para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'Age'] = df['Age'].fillna(median_age)

# Verificar si quedan valores NaN en la columna 'Age' después de la imputación.
print(f"\nNúmero de valores NaN en la columna 'Age' después de rellenar: {df['Age'].isnull().sum()}")

# Mostrar las primeras filas del DataFrame para verificar visualmente el cambio en la columna 'Age'.
print("\nPrimeras 5 filas del DataFrame con 'Age' rellenado:")
print(df.head())

# Mostrar la información del DataFrame (tipos de datos, conteo de no nulos) para confirmar el estado de 'Age'.
print("\nInformación del DataFrame después de rellenar 'Age':")
# Consejo: `df.info()` es una excelente herramienta para verificar rápidamente si las columnas tienen valores nulos y sus tipos de datos.
df.info()

Mediana de la columna 'Age': 28.0

Número de valores NaN en la columna 'Age' después de rellenar: 0

Primeras 5 filas del DataFrame con 'Age' rellenado:
  PlayerID   Age Region Platform PreferredGenre  SessionsPerWeek  \
0    P0001  22.0  LATAM       PC            RPG                3
1    P0002  21.0     EU       PC        Shooter                7
2    P0003  40.0  LATAM   Mobile        Shooter                3
3    P0004  37.0    NaN       PC        Shooter                0
4    P0005  28.0     EU  Console        Shooter                3

   AvgSessionMinutes  DaysSinceLastLogin  PlayerLevel  MatchesPlayedLast30D  \
0               87.0                  11           59                    14
1              113.0                   0           45                    24
2               67.0                   3           68                    27
3               48.0                   9           40                    39
4               90.0                  15           51                    15

   WinRate  InGamePurchase  FriendsInGame  UsesVoiceChat  \
0    0.481            7.38            3.0              1
1    0.475           11.56            8.0              1
2    0.341            0.42            6.0              1
3    0.225            8.83            NaN              1
4    0.454           23.86            0.0              0

   AchievementsUnlocked  ReportsReceivedLast30D  Churn30D
0                    17                       0         0
1                    21                       2         0
2                    26                       1         0
3                    41                       2         0
4                    35                       1         1

Información del DataFrame después de rellenar 'Age':
<class 'pandas.core.frame.DataFrame'>
Index: 550 entries, 0 to 549
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PlayerID                550 non-null    object
 1   Age                     550 non-null    float64
 2   Region                  421 non-null    object
 3   Platform                550 non-null    object
 4   PreferredGenre          550 non-null    object
 5   SessionsPerWeek         550 non-null    int64
 6   AvgSessionMinutes       538 non-null    float64
 7   DaysSinceLastLogin      550 non-null    int64
 8   PlayerLevel             550 non-null    int64
 9   MatchesPlayedLast30D    550 non-null    int64
 10  WinRate                 538 non-null    float64
 11  InGamePurchase          538 non-null    float64
 12  FriendsInGame           538 non-null    float64
 13  UsesVoiceChat           550 non-null    int64
 14  AchievementsUnlocked    550 non-null    int64
 15  ReportsReceivedLast30D  550 non-null    int64
 16  Churn30D                550 non-null    int64
dtypes: float64(5), int64(8), object(4)
memory usage: 77.3+ KB

In [37]:
# Mostrar el conteo de valores únicos en la columna 'Region' ANTES de realizar cambios.
# `dropna=False` incluye los valores NaN en el conteo, lo cual es útil para identificar faltantes.
print('Valores de la columna Region antes de los cambios:')
print(df['Region'].value_counts(dropna=False))

# Rellenar los valores NaN (faltantes) en la columna 'Region' con la cadena 'USA'.
# Esto asume que los valores faltantes corresponden a esta región por alguna razón de negocio o default.
df['Region'] = df['Region'].fillna('USA')

# Reemplazar la cadena 'Europe' por 'EU' en la columna 'Region' para estandarizar los nombres.
# Consejo: Es fundamental estandarizar las categorías en columnas de tipo 'object' para evitar inconsistencias.
df['Region'] = df['Region'].replace('Europe', 'EU')

# Mostrar el conteo de valores únicos en la columna 'Region' DESPUÉS de realizar los cambios.
print('\nValores de la columna Region después de los cambios:')
print(df['Region'].value_counts(dropna=False))

# Mostrar los valores únicos (distintos) presentes en la columna 'Region' para verificar la estandarización.
print('\nRegiones distintas en la columna Region después de los cambios:')
print(df['Region'].unique())
# Consejo: Para columnas categóricas, siempre revisa los valores únicos y sus conteos para detectar errores de entrada o inconsistencias.

Valores de la columna Region antes de los cambios:
Region
EU        211
NaN       129
APAC       81
LATAM      75
Europe     54
Name: count, dtype: int64

Valores de la columna Region después de los cambios:
Region
EU       265
USA      129
APAC      81
LATAM     75
Name: count, dtype: int64

Regiones distintas en la columna Region después de los cambios:
['LATAM' 'EU' 'USA' 'APAC']

In [38]:
# Obtener y mostrar los valores únicos de la columna 'Region' para verificar la limpieza.
distinct_regions = df['Region'].unique()
print(f"Regiones distintas en la columna 'Region': {distinct_regions}")

# Contar el número de valores NaN (faltantes) en la columna 'Region'.
# Esto confirma que los valores NaN fueron manejados correctamente.
num_nan_regions = df['Region'].isnull().sum()
print(f"Número de valores NaN (faltantes) en la columna 'Region': {num_nan_regions}")

# Informar si se encontraron valores NaN (aunque en este punto no deberían haber).
if num_nan_regions > 0:
    print("Estos valores 'nan' representan datos faltantes que pandas ha detectado o convertido.")

# Mostrar el conteo de valores por cada región, incluyendo NaN (si los hubiera, pero se espera 0).
# Esto sirve como una verificación final de la distribución de las categorías.
print("\nConteo de valores por cada región (incluyendo NaN):")
print(df['Region'].value_counts(dropna=False))
# Consejo: Siempre valida los resultados después de realizar operaciones de limpieza en columnas categóricas.

Regiones distintas en la columna 'Region': ['LATAM' 'EU' 'USA' 'APAC']
Número de valores NaN (faltantes) en la columna 'Region': 0

Conteo de valores por cada región (incluyendo NaN):
Region
EU       265
USA      129
APAC      81
LATAM     75
Name: count, dtype: int64

In [39]:
# Contar el número de plataformas únicas antes de cualquier cambio.
num_unique_platforms = df['Platform'].nunique()
print(f"Número de plataformas diferentes en la columna 'Platform': {num_unique_platforms}")

# Mostrar los nombres de las plataformas únicas antes de la estandarización.
print("Nombres de las plataformas únicas antes del cambio:")
print(df['Platform'].unique())

# Reemplazar la cadena 'pc' (minúscula) con 'PC' (mayúscula) para estandarizar los nombres de las plataformas.
# Esto es común en la limpieza de datos para manejar inconsistencias de capitalización.
df['Platform'] = df['Platform'].replace('pc', 'PC')

# Mostrar los nombres de las plataformas únicas después del cambio para verificar la estandarización.
print("\nNombres de las plataformas únicas después del cambio:")
print(df['Platform'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'Platform'.
num_nan_platforms = df['Platform'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'Platform': {num_nan_platforms}")

# Informar si se encontraron valores NaN (se espera que no haya en este caso).
if num_nan_platforms > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'Platform' (y no hay en este caso).")
# Consejo: Siempre busca y corrige inconsistencias de capitalización, espacios extra o errores tipográficos en columnas categóricas.

Número de plataformas diferentes en la columna 'Platform': 4
Nombres de las plataformas únicas antes del cambio:
['PC' 'Mobile' 'Console' 'pc']

Nombres de las plataformas únicas después del cambio:
['PC' 'Mobile' 'Console']

Número de valores NaN (faltantes) en la columna 'Platform': 0

In [40]:
# Mostrar los valores distintos (únicos) presentes en la columna 'PreferredGenre'.
# Esto ayuda a entender la variedad de géneros y detectar posibles errores o inconsistencias.
print("Valores distintos en 'PreferredGenre':")
print(df['PreferredGenre'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'PreferredGenre'.
num_nan_preferred_genre = df['PreferredGenre'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'PreferredGenre': {num_nan_preferred_genre}")

# Informar si se encontraron valores NaN.
if num_nan_preferred_genre > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'PreferredGenre'.")
# Consejo: Si hubiera NaN, una estrategia sería imputarlos con la moda (el género más frecuente) o 'Desconocido'.

# Mostrar el conteo de valores por cada género preferido, incluyendo NaN (si los hubiera).
# Esto proporciona una visión de la distribución de los géneros.
print("\nConteo de valores por cada género preferido (incluyendo NaN):")
print(df['PreferredGenre'].value_counts(dropna=False))

Valores distintos en 'PreferredGenre':
['RPG' 'Shooter' 'Strategy' 'Battle Royale' 'MOBA' 'Sports']

Número de valores NaN (faltantes) en la columna 'PreferredGenre': 0

Conteo de valores por cada género preferido (incluyendo NaN):
PreferredGenre
Battle Royale    100
Strategy          93
Sports            93
RPG               92
MOBA              87
Shooter           85
Name: count, dtype: int64

In [41]:
# Mostrar los valores distintos (únicos) presentes en la columna 'SessionsPerWeek'.
# Esto permite identificar el rango y la granularidad de los datos de sesiones por semana.
print("Valores distintos en 'SessionsPerWeek':")
print(df['SessionsPerWeek'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'SessionsPerWeek'.
num_nan_sessions_per_week = df['SessionsPerWeek'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'SessionsPerWeek': {num_nan_sessions_per_week}")

# Informar si se encontraron valores NaN.
if num_nan_sessions_per_week > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'SessionsPerWeek'.")
# Consejo: Si hubiera NaN, la imputación con la mediana o la moda sería apropiada para una variable de conteo como esta.

# Mostrar el conteo de valores por cada número de sesiones por semana, incluyendo NaN (si los hubiera).
# Esto ofrece una vista de la distribución de la frecuencia de juego.
print("\nConteo de valores por cada SessionsPerWeek (incluyendo NaN):")
print(df['SessionsPerWeek'].value_counts(dropna=False))

Valores distintos en 'SessionsPerWeek':
[ 3  7  0  5  4  6  8  2 10  1  9]

Número de valores NaN (faltantes) en la columna 'SessionsPerWeek': 0

Conteo de valores por cada SessionsPerWeek (incluyendo NaN):
SessionsPerWeek
4     106
3     104
5     101
6      86
7      51
2      36
1      27
8      24
0       6
9       5
10      4
Name: count, dtype: int64

In [42]:
# Mostrar los valores distintos en la columna 'AvgSessionMinutes' ANTES de rellenar los NaN.
# Esto permite ver la presencia de NaN antes de la imputación.
print("Valores distintos en 'AvgSessionMinutes' antes de rellenar NaN:")
print(df['AvgSessionMinutes'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'AvgSessionMinutes' ANTES de la imputación.
num_nan_avg_session_minutes_before = df['AvgSessionMinutes'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'AvgSessionMinutes' ANTES de rellenar: {num_nan_avg_session_minutes_before}")

# Calcular la mediana de 'AvgSessionMinutes'. La mediana es preferible a la media si la distribución es asimétrica (skewed).
median_avg_session_minutes = df['AvgSessionMinutes'].median()
print(f"Mediana calculada para 'AvgSessionMinutes': {median_avg_session_minutes}")

# Rellenar los valores NaN en la columna 'AvgSessionMinutes' con la mediana calculada.
df['AvgSessionMinutes'] = df['AvgSessionMinutes'].fillna(median_avg_session_minutes)

# Mostrar los valores distintos en 'AvgSessionMinutes' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'AvgSessionMinutes' DESPUÉS de rellenar NaN:")
print(df['AvgSessionMinutes'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'AvgSessionMinutes' DESPUÉS de la imputación.
num_nan_avg_session_minutes_after = df['AvgSessionMinutes'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'AvgSessionMinutes' DESPUÉS de rellenar: {num_nan_avg_session_minutes_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_avg_session_minutes_after == 0:
    print("Todos los valores NaN en 'AvgSessionMinutes' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'AvgSessionMinutes', incluyendo NaN (si los hubiera, se espera 0).
# Esto permite una verificación final de la distribución de los datos.
print("\nConteo de valores por cada AvgSessionMinutes (incluyendo NaN después de rellenar):")
print(df['AvgSessionMinutes'].value_counts(dropna=False))

Valores distintos en 'AvgSessionMinutes' antes de rellenar NaN:
[ 87. 113.  67.  48.  90.  32.  25.  66.  70.  72. 109.  nan 138. 119.
 151.  71.  76.  57. 123. 102.  44. 420. 101.  59. 116.  63. 103.  69.
  99. 105.  94.  51.  55.  45. 122. 510.  10. 124. 114.  85.  86.  88.
  77.  47.  92.  41.  43.  15.  78.  58.  65.  75.  96.  38.  61.  89.
  50.  98.  84.  33.  40.  73.  83.  49.  80. 104. 120.  81. 600.  64.
  97.  56.  68.  62.  30. 125. 154.  91.  79.  82.  52. 110.  74.  53.
  34.  95.  93. 100. 127. 117. 108.  11.  21.  46. 107.  27. 106.  22.
  60. 112. 115.  54.  39. 145. 139. 137. 126.  19. 111. 134.  14.  36.
  23.  37.  31.  26. 118.]

Número de valores NaN (faltantes) en la columna 'AvgSessionMinutes' ANTES de rellenar: 12
Mediana calculada para 'AvgSessionMinutes': 76.0

Valores distintos en 'AvgSessionMinutes' DESPUÉS de rellenar NaN:
[ 87. 113.  67.  48.  90.  32.  25.  66.  70.  72. 109.  76. 138. 119.
 151.  71.  57. 123. 102.  44. 420. 101.  59. 116.  63. 103.  69.  99.
 105.  94.  51.  55.  45. 122. 510.  10. 124. 114.  85.  86.  88.  77.
  47.  92.  41.  43.  15.  78.  58.  65.  75.  96.  38.  61.  89.  50.
  98.  84.  33.  40.  73.  83.  49.  80. 104. 120.  81. 600.  64.  97.
  56.  68.  62.  30. 125. 154.  91.  79.  82.  52. 110.  74.  53.  34.
  95.  93. 100. 127. 117. 108.  11.  21.  46. 107.  27. 106.  22.  60.
 112. 115.  54.  39. 145. 139. 137. 126.  19. 111. 134.  14.  36.  23.
  37.  31.  26. 118.]

Número de valores NaN (faltantes) en la columna 'AvgSessionMinutes' DESPUÉS de rellenar: 0
Todos los valores NaN en 'AvgSessionMinutes' han sido rellenados con éxito.

Conteo de valores por cada AvgSessionMinutes (incluyendo NaN después de rellenar):
AvgSessionMinutes
76.0     19
68.0     15
75.0     13
66.0     13
74.0     12
         ..
23.0      1
37.0      1
31.0      1
26.0      1
118.0     1
Name: count, Length: 116, dtype: int64

In [43]:
# Mostrar los valores distintos (únicos) presentes en la columna 'DaysSinceLastLogin'.
# Esto da una idea del comportamiento de inicio de sesión de los jugadores.
print("Valores distintos en 'DaysSinceLastLogin':")
print(df['DaysSinceLastLogin'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'DaysSinceLastLogin'.
num_nan_days_since_last_login = df['DaysSinceLastLogin'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'DaysSinceLastLogin': {num_nan_days_since_last_login}")

# Informar si se encontraron valores NaN.
if num_nan_days_since_last_login > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'DaysSinceLastLogin'.")
# Consejo: Para una variable de conteo como esta, si hubiera NaN, la mediana o la moda serían buenas opciones de imputación.

# Mostrar el conteo de valores por cada 'DaysSinceLastLogin', incluyendo NaN (si los hubiera).
# Esto proporciona una distribución de cuánto tiempo ha pasado desde el último inicio de sesión.
print("\nConteo de valores por cada DaysSinceLastLogin (incluyendo NaN):")
print(df['DaysSinceLastLogin'].value_counts(dropna=False))

Valores distintos en 'DaysSinceLastLogin':
[11  0  3  9 15 10  6 13 16  1  5  7 14  8  2 22 21  4 23 12 26 17 18 19
 20 25 24]

Número de valores NaN (faltantes) en la columna 'DaysSinceLastLogin': 0

Conteo de valores por cada DaysSinceLastLogin (incluyendo NaN):
DaysSinceLastLogin
0     97
10    38
9     36
6     34
5     32
7     32
11    31
3     29
8     28
12    24
4     23
13    21
1     19
14    18
15    15
2     15
16    12
17    12
18     8
22     6
21     6
20     4
19     4
23     2
25     2
26     1
24     1
Name: count, dtype: int64

In [44]:
# Mostrar los valores distintos (únicos) presentes en la columna 'PlayerLevel'.
# Esto revela el rango de niveles de los jugadores en el dataset.
print("Valores distintos en 'PlayerLevel':")
print(df['PlayerLevel'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'PlayerLevel'.
num_nan_player_level = df['PlayerLevel'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'PlayerLevel': {num_nan_player_level}")

# Informar si se encontraron valores NaN y si no se encontraron.
if num_nan_player_level > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'PlayerLevel'.")
# Consejo: Si hubiera NaN, la imputación con la mediana o la moda sería adecuada para una variable discreta como el nivel de jugador.
else:
    print("No se encontraron valores NaN en la columna 'PlayerLevel'.")

# Mostrar el conteo de valores por cada nivel de jugador, incluyendo NaN (si los hubiera).
# Esto ofrece una distribución de los niveles de los jugadores.
print("\nConteo de valores por cada nivel de jugador (incluyendo NaN):")
print(df['PlayerLevel'].value_counts(dropna=False))

Valores distintos en 'PlayerLevel':
[59 45 68 40 51 33 41 30  1  9 36 46 31 32 47 48 54 27 50 39 26 14 43 42
 61 24 71 35  5 15 29 16 37 49 67 17 44 38 10 58  7 79 62 52 20 63 22 57
 60 23 11 73  4 76 56 28 19 21  2 25 55 13 69 66 34 65 86 74  8 53  6 18
 12 72 70]

Número de valores NaN (faltantes) en la columna 'PlayerLevel': 0
No se encontraron valores NaN en la columna 'PlayerLevel'.

Conteo de valores por cada nivel de jugador (incluyendo NaN):
PlayerLevel
1     19
38    18
40    16
35    16
37    16
      ..
57     1
65     1
74     1
72     1
70     1
Name: count, Length: 75, dtype: int64

In [45]:
# Mostrar los valores distintos (únicos) presentes en la columna 'MatchesPlayedLast30D'.
# Esto da una idea de la actividad de juego de los usuarios en el último mes.
print("Valores distintos en 'MatchesPlayedLast30D':")
print(df['MatchesPlayedLast30D'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'MatchesPlayedLast30D'.
num_nan_matches_played = df['MatchesPlayedLast30D'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'MatchesPlayedLast30D': {num_nan_matches_played}")

# Informar si se encontraron valores NaN y si no se encontraron.
if num_nan_matches_played > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'MatchesPlayedLast30D'.")
# Consejo: Si hubiera NaN, la imputación con la mediana o la moda podría ser considerada.
else:
    print("No se encontraron valores NaN en la columna 'MatchesPlayedLast30D'.")

# Mostrar el conteo de valores por cada 'MatchesPlayedLast30D', incluyendo NaN (si los hubiera).
# Esto proporciona una distribución de la cantidad de partidas jugadas.
print("\nConteo de valores por cada 'MatchesPlayedLast30D' (incluyendo NaN):")
print(df['MatchesPlayedLast30D'].value_counts(dropna=False))

Valores distintos en 'MatchesPlayedLast30D':
[14 24 27 39 15 35 50 40 13 33 20 46  6 25 32 21 56 17  9 22 23 26  1 28
  0 38 29 52 18  5 63 19 37 47  7 44 10  4 58 41 45 53 34  8 30 12 43 31
 62 42 16 11  3 51 36 64 54 48 61  2 68 55 69 57]

Número de valores NaN (faltantes) en la columna 'MatchesPlayedLast30D': 0
No se encontraron valores NaN en la columna 'MatchesPlayedLast30D'.

Conteo de valores por cada 'MatchesPlayedLast30D' (incluyendo NaN):
MatchesPlayedLast30D
0     24
33    18
26    18
25    17
28    17
      ..
63     1
62     1
61     1
68     1
69     1
Name: count, Length: 64, dtype: int64

In [55]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 0
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [46]:
# Mostrar los valores distintos en la columna 'WinRate' ANTES de rellenar los NaN.
print("Valores distintos en 'WinRate' antes de rellenar NaN:")
print(df['WinRate'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'WinRate' ANTES de la imputación.
num_nan_win_rate_before = df['WinRate'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'WinRate' ANTES de rellenar: {num_nan_win_rate_before}")

# Calcular la media de 'WinRate'. La media es una opción común para variables numéricas continuas.
mean_win_rate = df['WinRate'].mean()
print(f"Media calculada para 'WinRate': {mean_win_rate:.3f}")

# Rellenar los valores NaN en la columna 'WinRate' con la media calculada.
# `df.loc[:, 'WinRate']` se usa para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'WinRate'] = df['WinRate'].fillna(mean_win_rate)

# Mostrar los valores distintos en 'WinRate' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'WinRate' DESPUÉS de rellenar NaN:")
print(df['WinRate'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'WinRate' DESPUÉS de la imputación.
num_nan_win_rate_after = df['WinRate'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'WinRate' DESPUÉS de rellenar: {num_nan_win_rate_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_win_rate_after == 0:
    print("Todos los valores NaN en 'WinRate' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'WinRate', incluyendo NaN (si los hubiera, se espera 0).
print("\nConteo de valores por cada 'WinRate' (incluyendo NaN después de rellenar):")
print(df['WinRate'].value_counts(dropna=False))

Valores distintos en 'WinRate' antes de rellenar NaN:
[0.481 0.475 0.341 0.225 0.454 0.61  0.422 0.303 0.711 0.796 0.638 0.51
 0.679 0.21  0.509 0.617 0.707 0.399 0.532 0.45  0.378 0.579 0.588 0.424
 0.619   nan 0.736 0.493 0.779 0.738 0.48  0.507 0.733 0.691 0.56  0.643
 0.506 0.508 0.826 0.427 0.585 0.62  0.409 0.831 0.841 0.433 0.783 0.413
 0.542 0.496 0.919 0.384 0.657 0.55  0.608 0.587 0.242 0.416 0.592 0.891
 0.198 0.4   0.376 0.42  0.95  0.802 0.52  0.572 0.368 0.439 0.662 0.361
 0.641 0.487 0.827 0.68  0.593 0.535 0.308 0.769 0.501 0.411 0.613 0.604
 0.661 0.669 0.557 0.264 0.477 0.455 0.546 0.5   0.47  0.524 0.392 0.548
 0.467 0.544 0.632 0.469 0.528 0.734 0.497 0.462 0.624 0.541 0.502 0.369
 0.589 0.663 0.261 0.474 0.458 0.495 0.714 0.511 0.397 0.672 0.332 0.568
 0.349 0.438 0.666 0.712 0.442 0.596 0.595 0.516 0.281 0.649 0.419 0.377
 0.543 0.396 0.425 0.484 0.277 0.226 0.536 0.284 0.525 0.37  0.551 0.457
 0.407 0.386 0.618 0.494 0.584 0.443 0.446 0.257 0.263 0.421 0.301 0.697
 0.569 0.379 0.644 0.545 0.708 0.464 0.459 0.577 0.699 0.718 0.212 0.69
 0.167 0.34  0.565 0.758 0.598 0.554 0.654 0.547 0.505 0.694 0.324 0.703
 0.575 0.232 0.388 0.756 0.567 0.581 0.65  0.573 0.49  0.197 0.471 0.762
 0.193 0.512 0.53  0.372 0.561 0.441 0.352 0.468 0.327 0.415 0.698 0.562
 0.517 0.398 0.659 0.597 0.915 0.461 0.268 0.533 0.426 0.164 0.485 0.279
 0.563 0.299 0.348 0.576 0.491 0.126 0.35  0.476 0.354 0.123 0.677 0.463
 0.622 0.363 0.521 0.394 0.552 0.138 0.43  0.531 0.2   0.306 0.165 0.676
 0.78  0.743 0.75  0.298 0.408 0.582 0.875 0.629 0.571 0.527 0.682 0.77
 0.177 0.79  0.405 0.351 0.336 0.728 0.184 0.23  0.229 0.526 0.642 0.515
 0.64  0.224 0.72  0.586 0.465 0.375 0.401 0.627 0.626 0.603 0.404 0.357
 0.323 0.233 0.692 0.452 0.591 0.449 0.693 0.488 0.578 0.553 0.63  0.656
 0.794 0.479 0.636 0.646 0.805 0.132 0.866 0.775 0.33  0.683 0.22  0.514
 0.437 0.172 0.778 0.456 0.673 0.402 0.594 0.665 0.609 0.559 0.239 0.653
 0.432 0.924 0.218 0.444 0.345 0.297 0.616 0.313 0.365 0.41  0.448 0.466
 0.153 0.601 0.362 0.335 0.374 0.478 0.645 0.429 0.519 0.558 0.631 0.686
 0.717 0.451 0.695 0.668 0.414 0.621 0.423 0.486 0.723 0.309 0.513 0.674
 0.343 0.675 0.658 0.381 0.713 0.564 0.129 0.236 0.539]

Número de valores NaN (faltantes) en la columna 'WinRate' ANTES de rellenar: 12
Media calculada para 'WinRate': 0.512

Valores distintos en 'WinRate' DESPUÉS de rellenar NaN:
[0.481      0.475      0.341      0.225      0.454      0.61
 0.422      0.303      0.711      0.796      0.638      0.51
 0.679      0.21       0.509      0.617      0.707      0.399
 0.532      0.45       0.378      0.579      0.588      0.424
 0.619      0.51248327 0.736      0.493      0.779      0.738
 0.48       0.507      0.733      0.691      0.56       0.643
 0.506      0.508      0.826      0.427      0.585      0.62
 0.409      0.831      0.841      0.433      0.783      0.413
 0.542      0.496      0.919      0.384      0.657      0.55
 0.608      0.587      0.242      0.416      0.592      0.891
 0.198      0.4        0.376      0.42       0.95       0.802
 0.52       0.572      0.368      0.439      0.662      0.361
 0.641      0.487      0.827      0.68       0.593      0.535
 0.308      0.769      0.501      0.411      0.613      0.604
 0.661      0.669      0.557      0.264      0.477      0.455
 0.546      0.5        0.47       0.524      0.392      0.548
 0.467      0.544      0.632      0.469      0.528      0.734
 0.497      0.462      0.624      0.541      0.502      0.369
 0.589      0.663      0.261      0.474      0.458      0.495
 0.714      0.511      0.397      0.672      0.332      0.568
 0.349      0.438      0.666      0.712      0.442      0.596
 0.595      0.516      0.281      0.649      0.419      0.377
 0.543      0.396      0.425      0.484      0.277      0.226
 0.536      0.284      0.525      0.37       0.551      0.457
 0.407      0.386      0.618      0.494      0.584      0.443
 0.446      0.257      0.263      0.421      0.301      0.697
 0.569      0.379      0.644      0.545      0.708      0.464
 0.459      0.577      0.699      0.718      0.212      0.69
 0.167      0.34       0.565      0.758      0.598      0.554
 0.654      0.547      0.505      0.694      0.324      0.703
 0.575      0.232      0.388      0.756      0.567      0.581
 0.65       0.573      0.49       0.197      0.471      0.762
 0.193      0.512      0.53       0.372      0.561      0.441
 0.352      0.468      0.327      0.415      0.698      0.562
 0.517      0.398      0.659      0.597      0.915      0.461
 0.268      0.533      0.426      0.164      0.485      0.279
 0.563      0.299      0.348      0.576      0.491      0.126
 0.35       0.476      0.354      0.123      0.677      0.463
 0.622      0.363      0.521      0.394      0.552      0.138
 0.43       0.531      0.2        0.306      0.165      0.676
 0.78       0.743      0.75       0.298      0.408      0.582
 0.875      0.629      0.571      0.527      0.682      0.77
 0.177      0.79       0.405      0.351      0.336      0.728
 0.184      0.23       0.229      0.526      0.642      0.515
 0.64       0.224      0.72       0.586      0.465      0.375
 0.401      0.627      0.626      0.603      0.404      0.357
 0.323      0.233      0.692      0.452      0.591      0.449
 0.693      0.488      0.578      0.553      0.63       0.656
 0.794      0.479      0.636      0.646      0.805      0.132
 0.866      0.775      0.33       0.683      0.22       0.514
 0.437      0.172      0.778      0.456      0.673      0.402
 0.594      0.665      0.609      0.559      0.239      0.653
 0.432      0.924      0.218      0.444      0.345      0.297
 0.616      0.313      0.365      0.41       0.448      0.466
 0.153      0.601      0.362      0.335      0.374      0.478
 0.645      0.429      0.519      0.558      0.631      0.686
 0.717      0.451      0.695      0.668      0.414      0.621
 0.423      0.486      0.723      0.309      0.513      0.674
 0.343      0.675      0.658      0.381      0.713      0.564
 0.129      0.236      0.539     ]

Número de valores NaN (faltantes) en la columna 'WinRate' DESPUÉS de rellenar: 0
Todos los valores NaN en 'WinRate' han sido rellenados con éxito.

Conteo de valores por cada 'WinRate' (incluyendo NaN después de rellenar):
WinRate
0.512483    12
0.548000     4
0.508000     4
0.588000     4
0.680000     4
            ..
0.796000     1
0.374000     1
0.335000     1
0.362000     1
0.601000     1
Name: count, Length: 357, dtype: int64

In [56]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 0
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [47]:
# Mostrar los valores distintos en la columna 'FriendsInGame' ANTES de rellenar los NaN.
print("Valores distintos en 'FriendsInGame' antes de rellenar NaN:")
print(df['FriendsInGame'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'FriendsInGame' ANTES de la imputación.
num_nan_friends_in_game_before = df['FriendsInGame'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'FriendsInGame' ANTES de rellenar: {num_nan_friends_in_game_before}")

# Si hay valores NaN, proceder con la imputación.
if num_nan_friends_in_game_before > 0:
    # Calcular la media de 'FriendsInGame'. Dado que es un conteo, la media es una opción razonable.
    mean_friends_in_game = df['FriendsInGame'].mean()
    print(f"Media calculada para 'FriendsInGame': {mean_friends_in_game:.2f}")

    # Rellenar los valores NaN en la columna 'FriendsInGame' con la media calculada.
    # Se utiliza `df.loc[:, 'FriendsInGame']` para evitar advertencias y asegurar la modificación directa en `df`.
    df.loc[:, 'FriendsInGame'] = df['FriendsInGame'].fillna(mean_friends_in_game)

    # Mostrar los valores distintos en 'FriendsInGame' DESPUÉS de rellenar los NaN.
    print("\nValores distintos en 'FriendsInGame' DESPUÉS de rellenar NaN:")
    print(df['FriendsInGame'].unique())

    # Contar el número de valores NaN (faltantes) en la columna 'FriendsInGame' DESPUÉS de la imputación.
    num_nan_friends_in_game_after = df['FriendsInGame'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'FriendsInGame' DESPUÉS de rellenar: {num_nan_friends_in_game_after}")

    # Confirmar si todos los valores NaN han sido rellenados.
    if num_nan_friends_in_game_after == 0:
        print("Todos los valores NaN en 'FriendsInGame' han sido rellenados con éxito.")
# Si no hay NaN inicialmente, informar de ello.
else:
    print("No se encontraron valores NaN en la columna 'FriendsInGame'.")

# Mostrar el conteo de valores por cada 'FriendsInGame', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'FriendsInGame' (incluyendo NaN después de rellenar si aplica):")
print(df['FriendsInGame'].value_counts(dropna=False))

Valores distintos en 'FriendsInGame' antes de rellenar NaN:
[ 3.  8.  6. nan  0.  4.  1. 18. 10.  7.  5. 19.  9. 13. 14. 12. 16. 11.
  2. 15. 20. 25. 17. 21.]

Número de valores NaN (faltantes) en la columna 'FriendsInGame' ANTES de rellenar: 12
Media calculada para 'FriendsInGame': 7.59

Valores distintos en 'FriendsInGame' DESPUÉS de rellenar NaN:
[ 3.          8.          6.          7.58921933  0.          4.
  1.         18.         10.          7.          5.         19.
  9.         13.         14.         12.         16.         11.
  2.         15.         20.         25.         17.         21.        ]

Número de valores NaN (faltantes) en la columna 'FriendsInGame' DESPUÉS de rellenar: 0
Todos los valores NaN en 'FriendsInGame' han sido rellenados con éxito.

Conteo de valores por cada 'FriendsInGame' (incluyendo NaN después de rellenar si aplica):
FriendsInGame
7.000000     46
8.000000     45
6.000000     44
0.000000     43
9.000000     43
5.000000     41
10.000000    38
11.000000    30
3.000000     29
13.000000    29
2.000000     27
4.000000     24
12.000000    20
1.000000     19
14.000000    18
7.589219     12
15.000000    12
16.000000    11
18.000000     8
19.000000     4
17.000000     4
20.000000     1
25.000000     1
21.000000     1
Name: count, dtype: int64

In [57]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 0
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [48]:
# Mostrar los valores distintos en la columna 'UsesVoiceChat'.
# Esta columna es binaria (0 o 1).
print("Valores distintos en 'UsesVoiceChat':")
print(df['UsesVoiceChat'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'UsesVoiceChat'.
num_nan_uses_voice_chat = df['UsesVoiceChat'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'UsesVoiceChat': {num_nan_uses_voice_chat}")

# Si hay valores NaN, se procede a rellenarlos de manera probabilística.
if num_nan_uses_voice_chat > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'UsesVoiceChat'.")

    # Calcular la proporción de 0s y 1s en los datos existentes (no nulos).
    # `normalize=True` devuelve las frecuencias relativas.
    value_counts = df['UsesVoiceChat'].dropna().value_counts(normalize=True)
    prob_0 = value_counts.get(0, 0) # Probabilidad de 0 (no usa chat de voz)
    prob_1 = value_counts.get(1, 0) # Probabilidad de 1 (usa chat de voz)

    print(f"\nProporción de 0s (no usa chat de voz): {prob_0:.2f}")
    print(f"Proporción de 1s (usa chat de voz): {prob_1:.2f}")

    # Rellenar los valores NaN probabilísticamente, manteniendo la distribución original.
    # `np.random.choice` selecciona 0 o 1 basándose en las proporciones calculadas.
    import numpy as np
    fill_values = np.random.choice([0, 1], size=num_nan_uses_voice_chat, p=[prob_0, prob_1])

    # Obtener los índices de los valores NaN para asignar los valores rellenados.
    nan_indices = df[df['UsesVoiceChat'].isnull()].index

    # Asignar los valores rellenados a los NaN en el DataFrame.
    df.loc[nan_indices, 'UsesVoiceChat'] = fill_values

    print("\nValores distintos en 'UsesVoiceChat' DESPUÉS de rellenar NaN:")
    print(df['UsesVoiceChat'].unique())

    # Verificar nuevamente si quedan valores NaN después de la imputación.
    num_nan_uses_voice_chat_after = df['UsesVoiceChat'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'UsesVoiceChat' DESPUÉS de rellenar: {num_nan_uses_voice_chat_after}")

    # Confirmar si todos los valores NaN han sido rellenados.
    if num_nan_uses_voice_chat_after == 0:
        print("Todos los valores NaN en 'UsesVoiceChat' han sido rellenados con éxito.")
# Si no hay NaN inicialmente, informar de ello.
else:
    print("No se encontraron valores NaN en la columna 'UsesVoiceChat'.")

# Mostrar el conteo de valores por cada 'UsesVoiceChat', incluyendo NaN (se espera 0 después de rellenar).
print("\nConteo de valores por cada 'UsesVoiceChat' (incluyendo NaN después de rellenar si aplica):")
print(df['UsesVoiceChat'].value_counts(dropna=False))

Valores distintos en 'UsesVoiceChat':
[1 0]

Número de valores NaN (faltantes) en la columna 'UsesVoiceChat': 0
No se encontraron valores NaN en la columna 'UsesVoiceChat'.

Conteo de valores por cada 'UsesVoiceChat' (incluyendo NaN después de rellenar si aplica):
UsesVoiceChat
1    300
0    250
Name: count, dtype: int64

In [49]:
# Mostrar los valores distintos en la columna 'AchievementsUnlocked' ANTES de rellenar NaN.
print("Valores distintos en 'AchievementsUnlocked' antes de rellenar NaN:")
print(df['AchievementsUnlocked'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'AchievementsUnlocked' ANTES de la imputación.
num_nan_achievements_unlocked_before = df['AchievementsUnlocked'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'AchievementsUnlocked' ANTES de rellenar: {num_nan_achievements_unlocked_before}")

# Si hay valores NaN, proceder con la imputación.
if num_nan_achievements_unlocked_before > 0:
    # Calcular la media de 'AchievementsUnlocked'. Es una buena opción para variables de conteo si la distribución no es muy asimétrica.
    mean_achievements_unlocked = df['AchievementsUnlocked'].mean()
    print(f"Media calculada para 'AchievementsUnlocked': {mean_achievements_unlocked:.2f}")

    # Rellenar los valores NaN en la columna 'AchievementsUnlocked' con la media calculada.
    # Se utiliza `df.loc[:, 'AchievementsUnlocked']` para asegurar la modificación en el DataFrame original.
    df.loc[:, 'AchievementsUnlocked'] = df['AchievementsUnlocked'].fillna(mean_achievements_unlocked)

    # Mostrar los valores distintos en 'AchievementsUnlocked' DESPUÉS de rellenar NaN.
    print("\nValores distintos en 'AchievementsUnlocked' DESPUÉS de rellenar NaN:")
    print(df['AchievementsUnlocked'].unique())

    # Contar el número de valores NaN (faltantes) en la columna 'AchievementsUnlocked' DESPUÉS de la imputación.
    num_nan_achievements_unlocked_after = df['AchievementsUnlocked'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'AchievementsUnlocked' DESPUÉS de rellenar: {num_nan_achievements_unlocked_after}")

    # Confirmar si todos los valores NaN han sido rellenados.
    if num_nan_achievements_unlocked_after == 0:
        print("Todos los valores NaN en 'AchievementsUnlocked' han sido rellenados con éxito.")
# Si no hay NaN inicialmente, informar de ello.
else:
    print("No se encontraron valores NaN en la columna 'AchievementsUnlocked'.")

# Mostrar el conteo de valores por cada 'AchievementsUnlocked', incluyendo NaN (se espera 0 después de rellenar).
print("\nConteo de valores por cada 'AchievementsUnlocked' (incluyendo NaN después de rellenar si aplica):")
print(df['AchievementsUnlocked'].value_counts(dropna=False))

Valores distintos en 'AchievementsUnlocked' antes de rellenar NaN:
[17 21 26 41 35 25 16  9 36 15 30 32 28 23 44  2 14 31 24 38 61  5 18 43
  4 53  7 40 33 10 20 13  8  0 34  6 22 12 19 46  3 49 48 27 29 11 37 39
 42 45  1 50 47]

Número de valores NaN (faltantes) en la columna 'AchievementsUnlocked' ANTES de rellenar: 0
No se encontraron valores NaN en la columna 'AchievementsUnlocked'.

Conteo de valores por cada 'AchievementsUnlocked' (incluyendo NaN después de rellenar si aplica):
AchievementsUnlocked
17    21
21    21
0     21
24    20
15    20
16    19
23    19
22    19
28    18
34    18
18    18
27    18
20    16
26    15
30    15
14    14
31    14
33    13
29    13
25    13
35    12
11    12
12    12
10    11
41    11
9     11
36    10
13    10
19     9
32     8
4      8
40     8
2      8
7      8
5      7
38     7
37     7
8      7
1      5
43     4
44     4
39     4
42     3
6      3
53     3
46     3
3      3
47     2
61     1
49     1
48     1
45     1
50     1
Name: count, dtype: int64

In [58]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 0
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [50]:
# Mostrar los valores distintos en la columna 'ReportsReceivedLast30D' ANTES de rellenar NaN.
print("Valores distintos en 'ReportsReceivedLast30D' antes de rellenar NaN:")
print(df['ReportsReceivedLast30D'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' ANTES de la imputación.
num_nan_reports_received_before = df['ReportsReceivedLast30D'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' ANTES de rellenar: {num_nan_reports_received_before}")

# Si hay valores NaN, proceder con la imputación.
if num_nan_reports_received_before > 0:
    # Calcular la media de 'ReportsReceivedLast30D'. Una opción común para imputar valores faltantes en variables numéricas.
    mean_reports_received = df['ReportsReceivedLast30D'].mean()
    print(f"Media calculada para 'ReportsReceivedLast30D': {mean_reports_received:.2f}")

    # Rellenar los valores NaN en la columna 'ReportsReceivedLast30D' con la media calculada.
    # Se utiliza `df.loc[:, 'ReportsReceivedLast30D']` para asegurar la modificación en el DataFrame original.
    df.loc[:, 'ReportsReceivedLast30D'] = df['ReportsReceivedLast30D'].fillna(mean_reports_received)

    # Mostrar los valores distintos en 'ReportsReceivedLast30D' DESPUÉS de rellenar NaN.
    print("\nValores distintos en 'ReportsReceivedLast30D' DESPUÉS de rellenar NaN:")
    print(df['ReportsReceivedLast30D'].unique())

    # Contar el número de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' DESPUÉS de la imputación.
    num_nan_reports_received_after = df['ReportsReceivedLast30D'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' DESPUÉS de rellenar: {num_nan_reports_received_after}")

    # Confirmar si todos los valores NaN han sido rellenados.
    if num_nan_reports_received_after == 0:
        print("Todos los valores NaN en 'ReportsReceivedLast30D' han sido rellenados con éxito.")
# Si no hay NaN inicialmente, informar de ello.
else:
    print("No se encontraron valores NaN en la columna 'ReportsReceivedLast30D'.")

# Mostrar el conteo de valores por cada 'ReportsReceivedLast30D', incluyendo NaN (se espera 0 después de rellenar).
print("\nConteo de valores por cada 'ReportsReceivedLast30D' (incluyendo NaN después de rellenar si aplica):")
print(df['ReportsReceivedLast30D'].value_counts(dropna=False))

Valores distintos en 'ReportsReceivedLast30D' antes de rellenar NaN:
[0 2 1 5 3 4]

Número de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' ANTES de rellenar: 0
No se encontraron valores NaN en la columna 'ReportsReceivedLast30D'.

Conteo de valores por cada 'ReportsReceivedLast30D' (incluyendo NaN después de rellenar si aplica):
ReportsReceivedLast30D
1    200
0    192
2    107
3     31
4     15
5      5
Name: count, dtype: int64

In [51]:
# Mostrar los valores distintos en la columna 'Churn30D'.
# Esta columna es binaria, indicando si un jugador se fue en los últimos 30 días (1) o no (0).
print("Valores distintos en 'Churn30D':")
print(df['Churn30D'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'Churn30D'.
num_nan_churn30d = df['Churn30D'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'Churn30D': {num_nan_churn30d}")

# Si hay valores NaN, proceder a rellenarlos de manera probabilística.
if num_nan_churn30d > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'Churn30D'.")

    # Calcular la proporción de 0s y 1s en los datos existentes (no nulos).
    # `normalize=True` devuelve las frecuencias relativas, lo cual es clave para mantener la distribución.
    value_counts = df['Churn30D'].dropna().value_counts(normalize=True)
    prob_0 = value_counts.get(0, 0) # Probabilidad de no abandono (0)
    prob_1 = value_counts.get(1, 0) # Probabilidad de abandono (1)

    print(f"\nProporción de 0s (no churn): {prob_0:.2f}")
    print(f"Proporción de 1s (churn): {prob_1:.2f}")

    # Rellenar los valores NaN probabilísticamente, para preservar la distribución original de la variable objetivo.
    # `np.random.choice` es útil aquí para muestrear valores (0 o 1) basándose en las probabilidades.
    import numpy as np
    fill_values = np.random.choice([0, 1], size=num_nan_churn30d, p=[prob_0, prob_1])

    # Obtener los índices de los valores NaN.
    nan_indices = df[df['Churn30D'].isnull()].index

    # Asignar los valores rellenados a los NaN en el DataFrame.
    df.loc[nan_indices, 'Churn30D'] = fill_values

    print("\nValores distintos en 'Churn30D' DESPUÉS de rellenar NaN:")
    print(df['Churn30D'].unique())

    # Verificar nuevamente si quedan valores NaN.
    num_nan_churn30d_after = df['Churn30D'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'Churn30D' DESPUÉS de rellenar: {num_nan_churn30d_after}")

    # Confirmar si todos los valores NaN han sido rellenados con éxito.
    if num_nan_churn30d_after == 0:
        print("Todos los valores NaN en 'Churn30D' han sido rellenados con éxito.")
# Si no hay NaN inicialmente, informar de ello.
else:
    print("No se encontraron valores NaN en la columna 'Churn30D'.")

# Mostrar el conteo de valores por cada 'Churn30D', incluyendo NaN (se espera 0 después de rellenar).
# Esto es importante para entender el balance de clases en la variable objetivo.
print("\nConteo de valores por cada 'Churn30D' (incluyendo NaN después de rellenar si aplica):")
print(df['Churn30D'].value_counts(dropna=False))

Valores distintos en 'Churn30D':
[0 1]

Número de valores NaN (faltantes) en la columna 'Churn30D': 0
No se encontraron valores NaN en la columna 'Churn30D'.

Conteo de valores por cada 'Churn30D' (incluyendo NaN después de rellenar si aplica):
Churn30D
0    324
1    226
Name: count, dtype: int64

In [54]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 0
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [53]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 0
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [52]:
# Mostrar los valores distintos en la columna 'InGamePurchase' ANTES de rellenar los NaN.
print("Valores distintos en 'InGamePurchase' antes de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de la imputación.
num_nan_in_game_purchase_before = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: {num_nan_in_game_purchase_before}")

# Calcular la media de 'InGamePurchase'. La media es una opción común para variables numéricas continuas como esta.
mean_in_game_purchase = df['InGamePurchase'].mean()
print(f"Media calculada para 'InGamePurchase': {mean_in_game_purchase:.2f}")

# Rellenar los valores NaN en la columna 'InGamePurchase' con la media calculada.
# Se utiliza `df.loc[:, 'InGamePurchase']` para asegurar la modificación en el DataFrame original y evitar advertencias.
df.loc[:, 'InGamePurchase'] = df['InGamePurchase'].fillna(mean_in_game_purchase)

# Mostrar los valores distintos en 'InGamePurchase' DESPUÉS de rellenar los NaN para verificar la imputación.
print("\nValores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:")
print(df['InGamePurchase'].unique())

# Contar el número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de la imputación.
num_nan_in_game_purchase_after = df['InGamePurchase'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: {num_nan_in_game_purchase_after}")

# Confirmar si todos los valores NaN han sido rellenados.
if num_nan_in_game_purchase_after == 0:
    print("Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.")

# Mostrar el conteo de valores por cada 'InGamePurchase', incluyendo NaN (si los hubiera, se espera 0 después de rellenar).
print("\nConteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):")
print(df['InGamePurchase'].value_counts(dropna=False))

Valores distintos en 'InGamePurchase' antes de rellenar NaN:
[7.380e+00 1.156e+01 4.200e-01 8.830e+00 2.386e+01 3.230e+00 3.120e+00
 1.000e-02 4.281e+01 7.130e+00 2.480e+00 1.351e+01 5.150e+00 7.140e+00
 8.000e+00 5.840e+00 4.170e+00 4.770e+00 6.400e-01 2.040e+00 1.160e+00
 1.900e-01 3.899e+01 4.115e+01 5.690e+00 4.780e+00 6.660e+00 2.842e+01
 9.020e+00 1.185e+01 3.130e+00 2.412e+01 1.758e+01 2.294e+01 9.710e+00
 1.322e+01 1.928e+01 1.712e+01 3.330e+00 1.053e+01 1.521e+01 1.045e+01
 1.898e+01 2.140e+00 6.930e+00 2.692e+01 1.950e+00 1.800e+00 1.600e+01
 6.000e-02 4.100e-01 2.830e+00 8.250e+00 1.291e+01 9.990e+02 3.600e+00
 2.410e+00 2.125e+01 5.920e+00 2.120e+00 1.971e+01 4.500e+00 7.870e+00
 3.000e-01 8.870e+00       nan 2.990e+00 6.731e+01 1.090e+00 1.589e+01
 2.553e+01 1.100e-01 1.478e+01 7.080e+00 1.644e+01 2.914e+01 9.000e-01
 1.139e+01 1.578e+01 9.380e+00 5.090e+00 1.795e+01 1.079e+01 4.930e+00
 1.930e+00 3.968e+01 3.394e+01 3.119e+01 9.540e+00 7.830e+00 5.740e+00
 1.511e+01 2.030e+01 2.763e+01 1.602e+01 1.760e+00 8.780e+00 3.914e+01
 2.214e+01 8.550e+00 1.873e+01 1.119e+01 1.340e+00 6.750e+00 2.612e+01
 1.500e-01 5.980e+00 8.300e-01 4.238e+01 1.145e+01 1.150e+01 2.371e+01
 4.027e+01 7.430e+00 1.718e+01 2.000e-02 3.770e+00 1.018e+01 7.670e+00
 2.600e-01 1.125e+01 8.620e+00 3.517e+01 1.793e+01 5.410e+00 4.971e+01
 3.004e+01 5.756e+01 3.620e+00 2.200e-01 1.430e+00 4.990e+00 2.121e+01
 1.866e+01 8.800e-01 7.000e-02 3.600e-01 3.723e+01 9.570e+00 1.545e+01
 7.540e+00 1.047e+01 1.088e+01 3.800e-01 3.990e+01 2.390e+01 7.030e+00
 1.397e+01 8.600e-01 1.982e+01 2.389e+01 1.252e+01 2.984e+01 4.560e+00
 5.200e-01 1.240e+01 5.570e+00 2.670e+00 8.840e+00 1.336e+01 1.036e+01
 1.406e+01 1.974e+01 3.170e+00 6.190e+00 5.330e+00 9.940e+00 2.470e+00
 7.470e+00 6.590e+00 1.483e+01 2.270e+00 2.610e+00 1.917e+01 6.060e+00
 2.550e+00 1.232e+01 1.097e+01 7.180e+00 2.040e+01 3.410e+00 8.650e+00
 1.194e+01 6.900e-01 1.967e+01 3.399e+01 1.536e+01 3.380e+00 1.681e+01
 5.970e+00 1.577e+01 9.400e-01 1.283e+01 1.038e+01 9.600e-01 3.920e+00
 4.800e-01 4.350e+00 2.398e+01 7.600e+00 8.700e-01 1.948e+01 1.947e+01
 1.869e+01 2.500e-01 1.954e+01 3.970e+00 7.920e+00 1.850e+00 3.670e+00
 1.146e+01 6.200e-01 1.132e+01 3.908e+01 1.360e+01 7.700e-01 6.180e+00
 4.280e+00 3.430e+01 1.780e+00 7.900e+00 3.450e+00 2.050e+00 1.150e+00
 2.336e+01 3.020e+00 6.500e-01 3.500e-01 1.700e+00 6.300e-01 6.290e+00
 1.339e+01 5.054e+01 1.740e+01 1.299e+01 1.020e+00 2.991e+01 1.310e+00
 1.070e+00 1.158e+01 2.144e+01 2.739e+01 3.094e+01 8.460e+00 6.430e+00
 1.591e+01 1.590e+00 5.200e+00 1.064e+01 2.055e+01 3.654e+01 1.245e+01
 1.063e+01 2.390e+00 6.795e+01 1.575e+01 1.818e+01 6.440e+00 2.723e+01
 6.870e+00 1.923e+01 4.900e-01 5.490e+00 1.231e+01 1.951e+01 9.550e+00
 2.537e+01 6.478e+01 7.200e+00 3.610e+00 1.520e+00 7.220e+00 4.553e+01
 1.607e+01 2.090e+00 4.193e+01 1.186e+01 3.320e+00 2.990e+01 2.400e-01
 2.920e+00 1.100e+01 1.052e+01 5.100e-01 9.030e+00 4.070e+00 1.143e+01
 2.593e+01 4.590e+00 1.379e+01 1.330e+01 5.012e+01 8.040e+00 6.840e+00
 3.140e+00 1.449e+01 1.516e+01 2.102e+01 2.061e+01 3.300e-01 2.654e+01
 4.340e+00 1.657e+01 8.690e+00 2.490e+00 2.430e+01 8.960e+00 1.229e+01
 1.720e+00 1.419e+01 8.420e+00 1.180e+01 4.400e+01 2.345e+01 3.750e+00
 1.770e+00 1.696e+01 6.305e+01 1.495e+01 2.146e+01 2.714e+01 8.680e+00
 3.710e+00 3.040e+00 1.203e+01 3.240e+00 4.780e+01 7.800e-01 2.564e+01
 1.890e+00 2.950e+00 2.160e+00 3.931e+01 6.350e+00 8.810e+00 1.029e+01
 1.940e+00 5.280e+00 1.490e+00 7.660e+00 1.808e+01 1.710e+01 2.064e+01
 5.426e+01 5.660e+00 1.618e+01 2.170e+01 5.530e+00 3.350e+00 1.374e+01
 5.480e+00 2.419e+01 5.900e+00 3.164e+01 7.050e+00 5.780e+00 1.060e+00
 1.639e+01 1.436e+01 2.150e+00 8.520e+00 2.730e+00 1.915e+01 1.788e+01
 4.080e+00 1.390e+01 6.360e+00 1.000e+00 4.920e+00 5.470e+00 2.230e+00
 6.000e-01 1.089e+01 1.304e+01 1.443e+01 1.140e+00 1.740e+00 1.122e+01
 1.874e+01 2.044e+01 2.615e+01 5.000e-02 2.960e+01 6.100e-01 2.493e+01
 1.864e+01 8.820e+00 5.940e+00 6.790e+00 9.090e+00 1.744e+01 4.160e+00
 9.490e+00 2.314e+01 5.180e+00 2.349e+01 4.330e+00 4.910e+00 2.166e+01
 4.750e+00 8.450e+00 1.571e+01 3.921e+01 8.440e+00 4.020e+00 5.400e-01
 1.731e+01 1.660e+00 3.680e+00 1.240e+00 8.060e+00 1.066e+01 9.850e+00
 1.329e+01 7.040e+00 2.800e-01 2.600e+00 5.510e+00 1.512e+01 1.373e+01
 9.860e+00 5.190e+00 8.330e+00 2.142e+01 4.258e+01 5.000e-01 7.930e+00
 3.900e+00 1.630e+00 1.723e+01 1.390e+00 1.041e+01 6.650e+00 4.960e+00
 3.096e+01 4.600e+00 5.250e+00 6.340e+00 9.410e+00 3.480e+01 1.033e+01
 1.127e+01 1.760e+01 2.260e+00 2.706e+01 5.430e+00 3.810e+00 1.233e+01
 2.360e+01 6.450e+00 1.976e+01 1.005e+01 9.610e+00 7.000e-01 6.030e+00
 3.521e+01 9.620e+00 1.573e+01 1.135e+01 1.913e+01 1.600e+00 1.680e+00
 6.100e+00 1.248e+01 7.760e+00 3.580e+00 2.276e+01 7.690e+00 1.228e+01
 3.001e+01 1.800e-01 1.742e+01 1.126e+01 3.490e+00 4.900e+00 1.309e+01
 4.500e+02 2.020e+00 4.764e+01 3.290e+00 4.370e+01 1.118e+01 2.578e+01
 1.990e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' ANTES de rellenar: 12
Media calculada para 'InGamePurchase': 14.38

Valores distintos en 'InGamePurchase' DESPUÉS de rellenar NaN:
[7.38000000e+00 1.15600000e+01 4.20000000e-01 8.83000000e+00
 2.38600000e+01 3.23000000e+00 3.12000000e+00 1.00000000e-02
 4.28100000e+01 7.13000000e+00 2.48000000e+00 1.35100000e+01
 5.15000000e+00 7.14000000e+00 8.00000000e+00 5.84000000e+00
 4.17000000e+00 4.77000000e+00 6.40000000e-01 2.04000000e+00
 1.16000000e+00 1.90000000e-01 3.89900000e+01 4.11500000e+01
 5.69000000e+00 4.78000000e+00 6.66000000e+00 2.84200000e+01
 9.02000000e+00 1.18500000e+01 3.13000000e+00 2.41200000e+01
 1.75800000e+01 2.29400000e+01 9.71000000e+00 1.32200000e+01
 1.92800000e+01 1.71200000e+01 3.33000000e+00 1.05300000e+01
 1.52100000e+01 1.04500000e+01 1.89800000e+01 2.14000000e+00
 6.93000000e+00 2.69200000e+01 1.95000000e+00 1.80000000e+00
 1.60000000e+01 6.00000000e-02 4.10000000e-01 2.83000000e+00
 8.25000000e+00 1.29100000e+01 9.99000000e+02 3.60000000e+00
 2.41000000e+00 2.12500000e+01 5.92000000e+00 2.12000000e+00
 1.97100000e+01 4.50000000e+00 7.87000000e+00 3.00000000e-01
 8.87000000e+00 1.43818773e+01 2.99000000e+00 6.73100000e+01
 1.09000000e+00 1.58900000e+01 2.55300000e+01 1.10000000e-01
 1.47800000e+01 7.08000000e+00 1.64400000e+01 2.91400000e+01
 9.00000000e-01 1.13900000e+01 1.57800000e+01 9.38000000e+00
 5.09000000e+00 1.79500000e+01 1.07900000e+01 4.93000000e+00
 1.93000000e+00 3.96800000e+01 3.39400000e+01 3.11900000e+01
 9.54000000e+00 7.83000000e+00 5.74000000e+00 1.51100000e+01
 2.03000000e+01 2.76300000e+01 1.60200000e+01 1.76000000e+00
 8.78000000e+00 3.91400000e+01 2.21400000e+01 8.55000000e+00
 1.87300000e+01 1.11900000e+01 1.34000000e+00 6.75000000e+00
 2.61200000e+01 1.50000000e-01 5.98000000e+00 8.30000000e-01
 4.23800000e+01 1.14500000e+01 1.15000000e+01 2.37100000e+01
 4.02700000e+01 7.43000000e+00 1.71800000e+01 2.00000000e-02
 3.77000000e+00 1.01800000e+01 7.67000000e+00 2.60000000e-01
 1.12500000e+01 8.62000000e+00 3.51700000e+01 1.79300000e+01
 5.41000000e+00 4.97100000e+01 3.00400000e+01 5.75600000e+01
 3.62000000e+00 2.20000000e-01 1.43000000e+00 4.99000000e+00
 2.12100000e+01 1.86600000e+01 8.80000000e-01 7.00000000e-02
 3.60000000e-01 3.72300000e+01 9.57000000e+00 1.54500000e+01
 7.54000000e+00 1.04700000e+01 1.08800000e+01 3.80000000e-01
 3.99000000e+01 2.39000000e+01 7.03000000e+00 1.39700000e+01
 8.60000000e-01 1.98200000e+01 2.38900000e+01 1.25200000e+01
 2.98400000e+01 4.56000000e+00 5.20000000e-01 1.24000000e+01
 5.57000000e+00 2.67000000e+00 8.84000000e+00 1.33600000e+01
 1.03600000e+01 1.40600000e+01 1.97400000e+01 3.17000000e+00
 6.19000000e+00 5.33000000e+00 9.94000000e+00 2.47000000e+00
 7.47000000e+00 6.59000000e+00 1.48300000e+01 2.27000000e+00
 2.61000000e+00 1.91700000e+01 6.06000000e+00 2.55000000e+00
 1.23200000e+01 1.09700000e+01 7.18000000e+00 2.04000000e+01
 3.41000000e+00 8.65000000e+00 1.19400000e+01 6.90000000e-01
 1.96700000e+01 3.39900000e+01 1.53600000e+01 3.38000000e+00
 1.68100000e+01 5.97000000e+00 1.57700000e+01 9.40000000e-01
 1.28300000e+01 1.03800000e+01 9.60000000e-01 3.92000000e+00
 4.80000000e-01 4.35000000e+00 2.39800000e+01 7.60000000e+00
 8.70000000e-01 1.94800000e+01 1.94700000e+01 1.86900000e+01
 2.50000000e-01 1.95400000e+01 3.97000000e+00 7.92000000e+00
 1.85000000e+00 3.67000000e+00 1.14600000e+01 6.20000000e-01
 1.13200000e+01 3.90800000e+01 1.36000000e+01 7.70000000e-01
 6.18000000e+00 4.28000000e+00 3.43000000e+01 1.78000000e+00
 7.90000000e+00 3.45000000e+00 2.05000000e+00 1.15000000e+00
 2.33600000e+01 3.02000000e+00 6.50000000e-01 3.50000000e-01
 1.70000000e+00 6.30000000e-01 6.29000000e+00 1.33900000e+01
 5.05400000e+01 1.74000000e+01 1.29900000e+01 1.02000000e+00
 2.99100000e+01 1.31000000e+00 1.07000000e+00 1.15800000e+01
 2.14400000e+01 2.73900000e+01 3.09400000e+01 8.46000000e+00
 6.43000000e+00 1.59100000e+01 1.59000000e+00 5.20000000e+00
 1.06400000e+01 2.05500000e+01 3.65400000e+01 1.24500000e+01
 1.06300000e+01 2.39000000e+00 6.79500000e+01 1.57500000e+01
 1.81800000e+01 6.44000000e+00 2.72300000e+01 6.87000000e+00
 1.92300000e+01 4.90000000e-01 5.49000000e+00 1.23100000e+01
 1.95100000e+01 9.55000000e+00 2.53700000e+01 6.47800000e+01
 7.20000000e+00 3.61000000e+00 1.52000000e+00 7.22000000e+00
 4.55300000e+01 1.60700000e+01 2.09000000e+00 4.19300000e+01
 1.18600000e+01 3.32000000e+00 2.99000000e+01 2.40000000e-01
 2.92000000e+00 1.10000000e+01 1.05200000e+01 5.10000000e-01
 9.03000000e+00 4.07000000e+00 1.14300000e+01 2.59300000e+01
 4.59000000e+00 1.37900000e+01 1.33000000e+01 5.01200000e+01
 8.04000000e+00 6.84000000e+00 3.14000000e+00 1.44900000e+01
 1.51600000e+01 2.10200000e+01 2.06100000e+01 3.30000000e-01
 2.65400000e+01 4.34000000e+00 1.65700000e+01 8.69000000e+00
 2.49000000e+00 2.43000000e+01 8.96000000e+00 1.22900000e+01
 1.72000000e+00 1.41900000e+01 8.42000000e+00 1.18000000e+01
 4.40000000e+01 2.34500000e+01 3.75000000e+00 1.77000000e+00
 1.69600000e+01 6.30500000e+01 1.49500000e+01 2.14600000e+01
 2.71400000e+01 8.68000000e+00 3.71000000e+00 3.04000000e+00
 1.20300000e+01 3.24000000e+00 4.78000000e+01 7.80000000e-01
 2.56400000e+01 1.89000000e+00 2.95000000e+00 2.16000000e+00
 3.93100000e+01 6.35000000e+00 8.81000000e+00 1.02900000e+01
 1.94000000e+00 5.28000000e+00 1.49000000e+00 7.66000000e+00
 1.80800000e+01 1.71000000e+01 2.06400000e+01 5.42600000e+01
 5.66000000e+00 1.61800000e+01 2.17000000e+01 5.53000000e+00
 3.35000000e+00 1.37400000e+01 5.48000000e+00 2.41900000e+01
 5.90000000e+00 3.16400000e+01 7.05000000e+00 5.78000000e+00
 1.06000000e+00 1.63900000e+01 1.43600000e+01 2.15000000e+00
 8.52000000e+00 2.73000000e+00 1.91500000e+01 1.78800000e+01
 4.08000000e+00 1.39000000e+01 6.36000000e+00 1.00000000e+00
 4.92000000e+00 5.47000000e+00 2.23000000e+00 6.00000000e-01
 1.08900000e+01 1.30400000e+01 1.44300000e+01 1.14000000e+00
 1.74000000e+00 1.12200000e+01 1.87400000e+01 2.04400000e+01
 2.61500000e+01 5.00000000e-02 2.96000000e+01 6.10000000e-01
 2.49300000e+01 1.86400000e+01 8.82000000e+00 5.94000000e+00
 6.79000000e+00 9.09000000e+00 1.74400000e+01 4.16000000e+00
 9.49000000e+00 2.31400000e+01 5.18000000e+00 2.34900000e+01
 4.33000000e+00 4.91000000e+00 2.16600000e+01 4.75000000e+00
 8.45000000e+00 1.57100000e+01 3.92100000e+01 8.44000000e+00
 4.02000000e+00 5.40000000e-01 1.73100000e+01 1.66000000e+00
 3.68000000e+00 1.24000000e+00 8.06000000e+00 1.06600000e+01
 9.85000000e+00 1.32900000e+01 7.04000000e+00 2.80000000e-01
 2.60000000e+00 5.51000000e+00 1.51200000e+01 1.37300000e+01
 9.86000000e+00 5.19000000e+00 8.33000000e+00 2.14200000e+01
 4.25800000e+01 5.00000000e-01 7.93000000e+00 3.90000000e+00
 1.63000000e+00 1.72300000e+01 1.39000000e+00 1.04100000e+01
 6.65000000e+00 4.96000000e+00 3.09600000e+01 4.60000000e+00
 5.25000000e+00 6.34000000e+00 9.41000000e+00 3.48000000e+01
 1.03300000e+01 1.12700000e+01 1.76000000e+01 2.26000000e+00
 2.70600000e+01 5.43000000e+00 3.81000000e+00 1.23300000e+01
 2.36000000e+01 6.45000000e+00 1.97600000e+01 1.00500000e+01
 9.61000000e+00 7.00000000e-01 6.03000000e+00 3.52100000e+01
 9.62000000e+00 1.57300000e+01 1.13500000e+01 1.91300000e+01
 1.60000000e+00 1.68000000e+00 6.10000000e+00 1.24800000e+01
 7.76000000e+00 3.58000000e+00 2.27600000e+01 7.69000000e+00
 1.22800000e+01 3.00100000e+01 1.80000000e-01 1.74200000e+01
 1.12600000e+01 3.49000000e+00 4.90000000e+00 1.30900000e+01
 4.50000000e+02 2.02000000e+00 4.76400000e+01 3.29000000e+00
 4.37000000e+01 1.11800000e+01 2.57800000e+01 1.99000000e+00]

Número de valores NaN (faltantes) en la columna 'InGamePurchase' DESPUÉS de rellenar: 0
Todos los valores NaN en 'InGamePurchase' han sido rellenados con éxito.

Conteo de valores por cada 'InGamePurchase' (incluyendo NaN después de rellenar):
InGamePurchase
14.381877    12
0.020000      4
2.270000      3
2.670000      3
2.120000      3
             ..
7.470000      1
2.470000      1
9.940000      1
5.330000      1
8.650000      1
Name: count, Length: 484, dtype: int64

In [59]:
print(df.to_string())

    PlayerID   Age Region Platform PreferredGenre  SessionsPerWeek  AvgSessionMinutes  DaysSinceLastLogin  PlayerLevel  MatchesPlayedLast30D   WinRate  InGamePurchase  FriendsInGame  UsesVoiceChat  AchievementsUnlocked  ReportsReceivedLast30D  Churn30D
0      P0001  22.0  LATAM       PC            RPG                3               87.0                  11           59                    14  0.481000        7.380000       3.000000              1                    17                       0         0
1      P0002  21.0     EU       PC        Shooter                7              113.0                   0           45                    24  0.475000       11.560000       8.000000              1                    21                       2         0
2      P0003  40.0  LATAM   Mobile        Shooter                3               67.0                   3           68                    27  0.341000        0.420000       6.000000              1                    26                       1         0
3      P0004  37.0    USA       PC        Shooter                0               48.0                   9           40                    39  0.225000        8.830000       7.589219              1                    41                       2         0
4      P0005  28.0     EU  Console        Shooter                3               90.0                  15           51                    15  0.454000       23.860000       0.000000              0                    35                       1         1
5      P0006  23.0    USA   Mobile       Strategy                5               32.0                  10           33                    35  0.610000        3.230000       4.000000              0                    25                       0         1
6      P0007  32.0    USA       PC  Battle Royale                5               25.0                   6           41                    50  0.422000        3.120000       6.000000              0                    16                       5         1
7      P0008  26.0     EU   Mobile           MOBA                3               66.0                  13           30                    40  0.303000        0.010000       1.000000              0                     9                       1         1
8      P0009  25.0  LATAM       PC           MOBA                5               70.0                   9            1                    13  0.711000       42.810000       0.000000              0                    21                       0         1
9      P0010  17.0     EU   Mobile        Shooter                4               72.0                  16            9                    33  0.796000        7.130000      18.000000              0                    36                       1         0
10     P0011  20.0     EU       PC            RPG                7              109.0                   1           36                    20  0.638000        2.480000       8.000000              1                    15                       0         0
11     P0012  34.0  LATAM   Mobile       Strategy                3               76.0                   6           46                    46  0.510000       13.510000       3.000000              1                    30                       1         1
12     P0013  31.0    USA       PC         Sports                7              138.0                   5           31                     6  0.679000        5.150000      10.000000              1                    25                       2         0
13     P0014  21.0     EU       PC       Strategy                6              119.0                  11           32                    25  0.210000        7.140000       7.000000              0                    17                       1         1
14     P0015  16.0  LATAM   Mobile  Battle Royale                6              151.0                   0           47                    32  0.509000        8.000000       7.000000              0                    32                       3         0
15     P0016  19.0     EU       PC       Strategy                5               71.0                   7           48                    21  0.617000        5.840000       5.000000              0                    32                       3         0
16     P0017  30.0     EU       PC        Shooter                7               76.0                  14           54                    13  0.707000        4.170000      10.000000              1                    28                       2         1
17     P0018  16.0   APAC   Mobile         Sports                4               57.0                   8           27                    56  0.399000        4.770000       8.000000              0                    23                       0         0
18     P0019  26.0     EU  Console            RPG                5               48.0                   2           47                    17  0.532000        0.640000      19.000000              1                    44                       3         1
19     P0020  34.0     EU       PC       Strategy                3               72.0                  11           50                     9  0.450000        2.040000       9.000000              1                     2                       1         0
20     P0021  22.0     EU       PC       Strategy                3              123.0                   0           39                    22  0.378000        1.160000       6.000000              1                    14                       0         1
21     P0022  31.0     EU  Console  Battle Royale                3              102.0                  22           26                    23  0.579000        0.190000       8.000000              1                    31                       5         0
22     P0023  27.0  LATAM       PC         Sports                8               44.0                  22            1                    25  0.588000       38.990000       5.000000              0                    24                       1         0
23     P0024  24.0     EU       PC       Strategy                8              420.0                  11           31                    26  0.424000       41.150000       0.000000              1                    38                       2         0
24     P0025  39.0    USA  Console        Shooter                5              101.0                  13           14                    15  0.619000        5.690000       6.000000              0                    61                       0         1
25     P0026  19.0     EU       PC            RPG                4               59.0                  21           54                     1  0.512483        4.780000      13.000000              1                    31                       1         0
26     P0027  22.0    USA       PC  Battle Royale                5              116.0                  14           43                    28  0.509000        6.660000       5.000000              1                     5                       0         1
27     P0028  21.0   APAC       PC       Strategy                7               63.0                   3           59                     0  0.736000       28.420000       7.000000              0                     9                       1         0
28     P0029  24.0    USA   Mobile       Strategy                6              103.0                   4            9                    15  0.493000        9.020000      14.000000              1                    18                       1         0
29     P0030  36.0    USA       PC           MOBA                5               76.0                  23           42                    21  0.779000       11.850000      12.000000              0                    24                       0         0
30     P0031  23.0  LATAM  Console       Strategy                3               69.0                   1           26                     9  0.738000        3.130000       4.000000              0                     5                       1         1
31     P0032  36.0    USA   Mobile         Sports                6               99.0                  13           61                    38  0.480000       24.120000      13.000000              1                    16                       0         1
32     P0033  40.0    USA       PC           MOBA                4              105.0                   0           24                    28  0.507000       17.580000       6.000000              0                     2                       2         1
33     P0034  17.0    USA       PC        Shooter                3               67.0                   9           71                    29  0.733000       22.940000      18.000000              1                    43                       1         0
34     P0035  30.0   APAC       PC           MOBA                6              105.0                   9           35                    52  0.691000        9.710000       9.000000              1                    16                       2         0
35     P0036  32.0   APAC  Console        Shooter                4               94.0                   6            5                    27  0.560000        4.780000       1.000000              0                    30                       0         0
36     P0037  26.0    USA  Console         Sports                5               51.0                   4           15                    27  0.643000       13.220000       5.000000              0                    16                       0         0
37     P0038  37.0    USA       PC        Shooter                2               70.0                   8            1                    26  0.506000       19.280000       4.000000              1                    24                       1         0
38     P0039  16.0  LATAM       PC  Battle Royale                5               55.0                   8           40                    27  0.508000       17.120000      16.000000              0                    25                       0         0
39     P0040  18.0   APAC   Mobile            RPG                5               99.0                   1           36                    50  0.512483        3.330000       4.000000              0                     4                       1         0
40     P0041  27.0     EU  Console         Sports                3               45.0                   0           27                    23  0.826000       10.530000      10.000000              1                    41                       1         0
41     P0042  35.0     EU   Mobile       Strategy                6              122.0                   0           45                    18  0.427000        2.480000       3.000000              1                    15                       0         1
42     P0043  23.0     EU  Console           MOBA                5              510.0                   7           43                    40  0.585000       15.210000       0.000000              1                    53                       0         1
43     P0044  19.0    USA       PC       Strategy                5               10.0                   4           29                     5  0.620000       10.450000       7.000000              1                     7                       0         0
44     P0045  25.0     EU  Console  Battle Royale                8              124.0                  12           16                    63  0.409000       18.980000       5.000000              1                    40                       1         0
45     P0046  16.0     EU       PC           MOBA                5              114.0                   7           37                    19  0.588000        2.140000       9.000000              1                    16                       1         1
46     P0047  40.0    USA   Mobile  Battle Royale                3              122.0                  11           40                    38  0.831000        6.930000       0.000000              0                    33                       1         1
47     P0048  22.0     EU  Console         Sports                2              103.0                  10           27                    37  0.841000       26.920000       5.000000              0                    26                       0         1
48     P0049  19.0     EU       PC            RPG                8               85.0                   5           49                    47  0.433000        1.950000      11.000000              1                    10                       2         0
49     P0050  20.0     EU       PC  Battle Royale                2               57.0                   0           24                    39  0.532000        1.800000       6.000000              1                    16                       1         0
50     P0051  20.0     EU       PC         Sports                5               86.0                   9           14                     7  0.783000       16.000000       3.000000              1                    20                       1         1
51     P0052  37.0   APAC       PC  Battle Royale               10               88.0                   3           32                    44  0.413000        0.060000       2.000000              1                     2                       2         0
52     P0053  32.0   APAC       PC         Sports                4               77.0                   6           40                    10  0.542000        0.410000       7.589219              0                    13                       0         1
53     P0054  32.0     EU       PC  Battle Royale                4               47.0                  26           36                    28  0.496000        2.830000       7.000000              0                    23                       0         1
54     P0055  23.0   APAC  Console           MOBA                1               92.0                   9           67                     4  0.919000        8.250000       6.000000              0                    24                       0         1
55     P0056  25.0     EU   Mobile       Strategy                6               41.0                   5           33                    35  0.384000       12.910000      11.000000              0                     8                       0         1
56     P0057  18.0     EU       PC       Strategy                5               99.0                  14           46                    28  0.509000      999.000000       6.000000              0                     9                       0         1
57     P0058  16.0  LATAM  Console  Battle Royale                5               43.0                  14           31                    20  0.657000        3.600000      14.000000              0                     0                       1         1
58     P0059  17.0    USA       PC        Shooter                4               86.0                   9           17                    27  0.550000        2.410000      19.000000              1                     0                       1         0
59     P0060  28.0     EU  Console           MOBA                2               77.0                   0           44                    58  0.608000       21.250000       9.000000              1                    33                       1         1
60     P0061  36.0    USA       PC       Strategy                5               15.0                   5           38                     6  0.587000        5.920000       3.000000              1                     5                       0         0
61     P0062  17.0  LATAM       PC        Shooter                6               72.0                   7           14                    32  0.242000        2.120000       9.000000              1                    24                       0         0
62     P0063  17.0   APAC       PC           MOBA                4              119.0                   3           67                    38  0.416000       19.280000       2.000000              1                    33                       1         1
63     P0064  32.0     EU  Console  Battle Royale                4               90.0                   9           10                    33  0.592000       19.710000      14.000000              1                    34                       0         0
64     P0065  30.0     EU       PC  Battle Royale                4               78.0                   5           37                     9  0.891000        4.500000       9.000000              0                    14                       0         0
65     P0066  33.0    USA       PC         Sports                7               10.0                  17           58                    41  0.198000        7.870000       8.000000              0                    34                       1         0
66     P0067  19.0   APAC       PC        Shooter                3              101.0                  14           40                     7  0.588000        0.300000       8.000000              1                    34                       2         0
67     P0068  36.0  LATAM       PC         Sports               10               58.0                   3            7                    24  0.400000        8.870000       0.000000              1                    18                       2         1
68     P0069  30.0    USA   Mobile       Strategy                1               44.0                   0           47                    25  0.376000       14.381877       7.000000              1                    30                       0         1
69     P0070  23.0  LATAM  Console        Shooter                5               87.0                  10           79                    18  0.420000        2.990000      10.000000              0                    14                       0         0
70     P0071  32.0    USA       PC        Shooter               10               86.0                   0           38                     0  0.950000       67.310000       7.000000              1                    33                       1         1
71     P0072  20.0     EU       PC         Sports                3               65.0                  10           41                    37  0.802000        1.090000       0.000000              0                     6                       2         1
72     P0073  28.0     EU       PC         Sports                6               75.0                  21           49                    44  0.520000       15.890000      13.000000              0                    22                       0         1
73     P0074  28.0     EU       PC         Sports                6               96.0                  15           62                    18  0.572000       25.530000       7.000000              0                    23                       1         0
74     P0075  29.0   APAC   Mobile        Shooter                3               96.0                  12            1                    23  0.368000        0.110000       6.000000              0                    24                       0         1
75     P0076  17.0     EU       PC        Shooter                7               38.0                   9           42                    25  0.439000       14.780000       8.000000              0                    13                       1         1
76     P0077  30.0     EU       PC           MOBA                5               61.0                   7            1                    38  0.662000        7.080000       0.000000              0                     0                       2         1
77     P0078  29.0     EU  Console           MOBA                4               66.0                   0           24                    45  0.361000       16.440000       9.000000              1                    18                       1         0