<a href="https://colab.research.google.com/github/AbnerJSV/THE_CORE_Trabajos_iA/blob/main/Telemetria_Videojuegos/TelemetriaDeVideojuegos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv('videojuegos_online_telemetria.csv')

# Mostrar las primeras filas del DataFrame
print('Primeras 5 filas del DataFrame:')
print(df.head())

Primeras 5 filas del DataFrame:
  PlayerID   Age Region Platform PreferredGenre  SessionsPerWeek  \
0    P0001  22.0  LATAM       PC            RPG                3
1    P0002  21.0     EU       PC        Shooter                7
2    P0003  40.0  LATAM   Mobile        Shooter                3
3    P0004  37.0    NaN       PC        Shooter                0
4    P0005  28.0     EU  Console        Shooter                3

   AvgSessionMinutes  DaysSinceLastLogin  PlayerLevel  MatchesPlayedLast30D  \
0               87.0                  11           59                    14
1              113.0                   0           45                    24
2               67.0                   3           68                    27
3               48.0                   9           40                    39
4               90.0                  15           51                    15

   WinRate  InGamePurchase  FriendsInGame  UsesVoiceChat  \
0    0.481            7.38            3.0              1
1    0.475           11.56            8.0              1
2    0.341            0.42            6.0              1
3    0.225            8.83            NaN              1
4    0.454           23.86            0.0              0

   AchievementsUnlocked  ReportsReceivedLast30D  Churn30D
0                    17                       0         0
1                    21                       2         0
2                    26                       1         0
3                    41                       2         0
4                    35                       1         1

In [3]:
# Contar el número de valores duplicados en la columna 'PlayerID'
num_duplicates = df['PlayerID'].duplicated().sum()

# Mostrar el resultado
if num_duplicates > 0:
    print(f"Se encontraron {num_duplicates} valores duplicados en la columna 'PlayerID'.")
    print("Las filas duplicadas (manteniendo la primera aparición) son:")
    display(df[df['PlayerID'].duplicated(keep='first')])
else:
    print("No se encontraron valores duplicados en la columna 'PlayerID'.")

Se encontraron 8 valores duplicados en la columna 'PlayerID'.
Las filas duplicadas (manteniendo la primera aparición) son:

,PlayerID,Age,Region,Platform,PreferredGenre,SessionsPerWeek,AvgSessionMinutes,DaysSinceLastLogin,PlayerLevel,MatchesPlayedLast30D,WinRate,InGamePurchase,FriendsInGame,UsesVoiceChat,AchievementsUnlocked,ReportsReceivedLast30D,Churn30D
550,P0196,31.0,LATAM,PC,RPG,4,127.0,2,56,33,0.545,20.40,0.0,1,28,0,0
551,P0080,37.0,NaN,pc,RPG,1,89.0,3,52,23,0.496,0.90,5.0,1,0,0,0
552,P0481,40.0,EU,PC,Sports,2,111.0,6,15,30,0.357,0.50,13.0,1,22,2,1
553,P0110,20.0,EU,Console,RPG,1,97.0,11,76,12,0.469,26.12,1.0,0,19,2,0
554,P0523,27.0,EU,PC,Shooter,3,91.0,7,27,3,0.513,1.60,15.0,1,27,4,0
555,P0533,28.0,EU,pc,Battle Royale,4,87.0,5,6,0,0.528,0.18,4.0,0,10,0,0
556,P0085,30.0,LATAM,PC,RPG,4,33.0,10,46,20,0.736,5.09,0.0,1,46,3,0
557,P0369,29.0,EU,PC,Sports,2,96.0,0,23,34,0.332,25.64,12.0,0,36,0,1

In [4]:
# Mostrar todas las filas que tienen valores duplicados en la columna 'PlayerID'
# Esto incluye la primera aparición de cada duplicado
duplicated_rows = df[df['PlayerID'].duplicated(keep=False)]

if not duplicated_rows.empty:
    print("Todas las filas con 'PlayerID' duplicados son:")
    display(duplicated_rows)
else:
    print("No se encontraron valores duplicados en la columna 'PlayerID'.")

Todas las filas con 'PlayerID' duplicados son:

,PlayerID,Age,Region,Platform,PreferredGenre,SessionsPerWeek,AvgSessionMinutes,DaysSinceLastLogin,PlayerLevel,MatchesPlayedLast30D,WinRate,InGamePurchase,FriendsInGame,UsesVoiceChat,AchievementsUnlocked,ReportsReceivedLast30D,Churn30D
79,P0080,37.0,NaN,pc,RPG,1,89.0,3,52,23,0.496,0.90,5.0,1,0,0,0
84,P0085,30.0,LATAM,PC,RPG,4,33.0,10,46,20,0.736,5.09,0.0,1,46,3,0
109,P0110,20.0,EU,Console,RPG,1,97.0,11,76,12,0.469,26.12,1.0,0,19,2,0
195,P0196,31.0,LATAM,PC,RPG,4,127.0,2,56,33,0.545,20.40,0.0,1,28,0,0
368,P0369,29.0,EU,PC,Sports,2,96.0,0,23,34,0.332,25.64,12.0,0,36,0,1
480,P0481,40.0,EU,PC,Sports,2,111.0,6,15,30,0.357,0.50,13.0,1,22,2,1
522,P0523,27.0,EU,PC,Shooter,3,91.0,7,27,3,0.513,1.60,15.0,1,27,4,0
532,P0533,28.0,EU,pc,Battle Royale,4,87.0,5,6,0,0.528,0.18,4.0,0,10,0,0
550,P0196,31.0,LATAM,PC,RPG,4,127.0,2,56,33,0.545,20.40,0.0,1,28,0,0
551,P0080,37.0,NaN,pc,RPG,1,89.0,3,52,23,0.496,0.90,5.0,1,0,0,0
552,P0481,40.0,EU,PC,Sports,2,111.0,6,15,30,0.357,0.50,13.0,1,22,2,1
553,P0110,20.0,EU,Console,RPG,1,97.0,11,76,12,0.469,26.12,1.0,0,19,2,0
554,P0523,27.0,EU,PC,Shooter,3,91.0,7,27,3,0.513,1.60,15.0,1,27,4,0
555,P0533,28.0,EU,pc,Battle Royale,4,87.0,5,6,0,0.528,0.18,4.0,0,10,0,0
556,P0085,30.0,LATAM,PC,RPG,4,33.0,10,46,20,0.736,5.09,0.0,1,46,3,0
557,P0369,29.0,EU,PC,Sports,2,96.0,0,23,34,0.332,25.64,12.0,0,36,0,1

In [5]:
# Eliminar filas duplicadas basándose en la columna 'PlayerID', conservando la primera aparición
df_cleaned = df.drop_duplicates(subset=['PlayerID'], keep='first')

# Mostrar el número de filas antes y después de la eliminación
print(f"Filas antes de eliminar duplicados: {df.shape[0]}")
print(f"Filas después de eliminar duplicados: {df_cleaned.shape[0]}")

# Actualizar el DataFrame original si se desea
df = df_cleaned.copy()

# Verificar si aún existen duplicados en 'PlayerID' para confirmar la eliminación
num_remaining_duplicates = df['PlayerID'].duplicated().sum()
if num_remaining_duplicates == 0:
    print("\nSe han eliminado todos los duplicados en la columna 'PlayerID'.")
else:
    print(f"\nTodavía quedan {num_remaining_duplicates} duplicados en 'PlayerID'.")

Filas antes de eliminar duplicados: 558
Filas después de eliminar duplicados: 550

Se han eliminado todos los duplicados en la columna 'PlayerID'.

### Manejo de valores faltantes en la columna 'Age'

Vamos a calcular la mediana de la columna 'Age' y usarla para rellenar los valores faltantes (NaN) en esta columna.

In [8]:
median_age = df['Age'].median()
print(f"Mediana de la columna 'Age': {median_age}")

df.loc[:, 'Age'] = df['Age'].fillna(median_age)

# Verificar si quedan valores NaN en la columna 'Age'
print(f"\nNúmero de valores NaN en la columna 'Age' después de rellenar: {df['Age'].isnull().sum()}")

# Mostrar las primeras filas para verificar el cambio
print("\nPrimeras 5 filas del DataFrame con 'Age' rellenado:")
print(df.head())

# Verificar con df.info() para más detalles
print("\nInformación del DataFrame después de rellenar 'Age':")
df.info()

Mediana de la columna 'Age': 28.0

Número de valores NaN en la columna 'Age' después de rellenar: 0

Primeras 5 filas del DataFrame con 'Age' rellenado:
  PlayerID   Age Region Platform PreferredGenre  SessionsPerWeek  \
0    P0001  22.0  LATAM       PC            RPG                3
1    P0002  21.0     EU       PC        Shooter                7
2    P0003  40.0  LATAM   Mobile        Shooter                3
3    P0004  37.0    NaN       PC        Shooter                0
4    P0005  28.0     EU  Console        Shooter                3

   AvgSessionMinutes  DaysSinceLastLogin  PlayerLevel  MatchesPlayedLast30D  \
0               87.0                  11           59                    14
1              113.0                   0           45                    24
2               67.0                   3           68                    27
3               48.0                   9           40                    39
4               90.0                  15           51                    15

   WinRate  InGamePurchase  FriendsInGame  UsesVoiceChat  \
0    0.481            7.38            3.0              1
1    0.475           11.56            8.0              1
2    0.341            0.42            6.0              1
3    0.225            8.83            NaN              1
4    0.454           23.86            0.0              0

   AchievementsUnlocked  ReportsReceivedLast30D  Churn30D
0                    17                       0         0
1                    21                       2         0
2                    26                       1         0
3                    41                       2         0
4                    35                       1         1

Información del DataFrame después de rellenar 'Age':
<class 'pandas.core.frame.DataFrame'>
Index: 550 entries, 0 to 549
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PlayerID                550 non-null    object
 1   Age                     550 non-null    float64
 2   Region                  421 non-null    object
 3   Platform                550 non-null    object
 4   PreferredGenre          550 non-null    object
 5   SessionsPerWeek         550 non-null    int64
 6   AvgSessionMinutes       538 non-null    float64
 7   DaysSinceLastLogin      550 non-null    int64
 8   PlayerLevel             550 non-null    int64
 9   MatchesPlayedLast30D    550 non-null    int64
 10  WinRate                 538 non-null    float64
 11  InGamePurchase          538 non-null    float64
 12  FriendsInGame           538 non-null    float64
 13  UsesVoiceChat           550 non-null    int64
 14  AchievementsUnlocked    550 non-null    int64
 15  ReportsReceivedLast30D  550 non-null    int64
 16  Churn30D                550 non-null    int64
dtypes: float64(5), int64(8), object(4)
memory usage: 77.3+ KB

In [13]:
print('Valores de la columna Region antes de los cambios:')
print(df['Region'].value_counts(dropna=False))

# Reemplazar valores NaN por 'USA'
df['Region'] = df['Region'].fillna('USA')

# Reemplazar 'Europe' por 'EU'
df['Region'] = df['Region'].replace('Europe', 'EU')

print('\nValores de la columna Region después de los cambios:')
print(df['Region'].value_counts(dropna=False))

# Verificar las regiones distintas después de los cambios
print('\nRegiones distintas en la columna Region después de los cambios:')
print(df['Region'].unique())

Valores de la columna Region antes de los cambios:
Region
EU        211
NaN       129
APAC       81
LATAM      75
Europe     54
Name: count, dtype: int64

Valores de la columna Region después de los cambios:
Region
EU       265
USA      129
APAC      81
LATAM     75
Name: count, dtype: int64

Regiones distintas en la columna Region después de los cambios:
['LATAM' 'EU' 'USA' 'APAC']

In [14]:
distinct_regions = df['Region'].unique()
print(f"Regiones distintas en la columna 'Region': {distinct_regions}")

num_nan_regions = df['Region'].isnull().sum()
print(f"Número de valores NaN (faltantes) en la columna 'Region': {num_nan_regions}")

if num_nan_regions > 0:
    print("Estos valores 'nan' representan datos faltantes que pandas ha detectado o convertido.")

print("\nConteo de valores por cada región (incluyendo NaN):")
print(df['Region'].value_counts(dropna=False))

Regiones distintas en la columna 'Region': ['LATAM' 'EU' 'USA' 'APAC']
Número de valores NaN (faltantes) en la columna 'Region': 0

Conteo de valores por cada región (incluyendo NaN):
Region
EU       265
USA      129
APAC      81
LATAM     75
Name: count, dtype: int64

In [17]:
num_unique_platforms = df['Platform'].nunique()
print(f"Número de plataformas diferentes en la columna 'Platform': {num_unique_platforms}")

print("Nombres de las plataformas únicas antes del cambio:")
print(df['Platform'].unique())

# Reemplazar 'pc' con 'PC'
df['Platform'] = df['Platform'].replace('pc', 'PC')

print("\nNombres de las plataformas únicas después del cambio:")
print(df['Platform'].unique())

num_nan_platforms = df['Platform'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'Platform': {num_nan_platforms}")

if num_nan_platforms > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'Platform' (y no hay en este caso).")

Número de plataformas diferentes en la columna 'Platform': 4
Nombres de las plataformas únicas antes del cambio:
['PC' 'Mobile' 'Console' 'pc']

Nombres de las plataformas únicas después del cambio:
['PC' 'Mobile' 'Console']

Número de valores NaN (faltantes) en la columna 'Platform': 0

In [18]:
print("Valores distintos en 'PreferredGenre':")
print(df['PreferredGenre'].unique())

num_nan_preferred_genre = df['PreferredGenre'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'PreferredGenre': {num_nan_preferred_genre}")

if num_nan_preferred_genre > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'PreferredGenre'.")

print("\nConteo de valores por cada género preferido (incluyendo NaN):")
print(df['PreferredGenre'].value_counts(dropna=False))

Valores distintos en 'PreferredGenre':
['RPG' 'Shooter' 'Strategy' 'Battle Royale' 'MOBA' 'Sports']

Número de valores NaN (faltantes) en la columna 'PreferredGenre': 0

Conteo de valores por cada género preferido (incluyendo NaN):
PreferredGenre
Battle Royale    100
Strategy          93
Sports            93
RPG               92
MOBA              87
Shooter           85
Name: count, dtype: int64

In [19]:
print("Valores distintos en 'SessionsPerWeek':")
print(df['SessionsPerWeek'].unique())

num_nan_sessions_per_week = df['SessionsPerWeek'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'SessionsPerWeek': {num_nan_sessions_per_week}")

if num_nan_sessions_per_week > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'SessionsPerWeek'.")

print("\nConteo de valores por cada SessionsPerWeek (incluyendo NaN):")
print(df['SessionsPerWeek'].value_counts(dropna=False))

Valores distintos en 'SessionsPerWeek':
[ 3  7  0  5  4  6  8  2 10  1  9]

Número de valores NaN (faltantes) en la columna 'SessionsPerWeek': 0

Conteo de valores por cada SessionsPerWeek (incluyendo NaN):
SessionsPerWeek
4     106
3     104
5     101
6      86
7      51
2      36
1      27
8      24
0       6
9       5
10      4
Name: count, dtype: int64

In [21]:
print("Valores distintos en 'AvgSessionMinutes' antes de rellenar NaN:")
print(df['AvgSessionMinutes'].unique())

num_nan_avg_session_minutes_before = df['AvgSessionMinutes'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'AvgSessionMinutes' ANTES de rellenar: {num_nan_avg_session_minutes_before}")

# Calcular la mediana de AvgSessionMinutes
median_avg_session_minutes = df['AvgSessionMinutes'].median()
print(f"Mediana calculada para 'AvgSessionMinutes': {median_avg_session_minutes}")

# Rellenar los valores NaN con la mediana
df['AvgSessionMinutes'] = df['AvgSessionMinutes'].fillna(median_avg_session_minutes)

print("\nValores distintos en 'AvgSessionMinutes' DESPUÉS de rellenar NaN:")
print(df['AvgSessionMinutes'].unique())

num_nan_avg_session_minutes_after = df['AvgSessionMinutes'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'AvgSessionMinutes' DESPUÉS de rellenar: {num_nan_avg_session_minutes_after}")

if num_nan_avg_session_minutes_after == 0:
    print("Todos los valores NaN en 'AvgSessionMinutes' han sido rellenados con éxito.")

print("\nConteo de valores por cada AvgSessionMinutes (incluyendo NaN después de rellenar):")
print(df['AvgSessionMinutes'].value_counts(dropna=False))

Valores distintos en 'AvgSessionMinutes' antes de rellenar NaN:
[ 87. 113.  67.  48.  90.  32.  25.  66.  70.  72. 109.  nan 138. 119.
 151.  71.  76.  57. 123. 102.  44. 420. 101.  59. 116.  63. 103.  69.
  99. 105.  94.  51.  55.  45. 122. 510.  10. 124. 114.  85.  86.  88.
  77.  47.  92.  41.  43.  15.  78.  58.  65.  75.  96.  38.  61.  89.
  50.  98.  84.  33.  40.  73.  83.  49.  80. 104. 120.  81. 600.  64.
  97.  56.  68.  62.  30. 125. 154.  91.  79.  82.  52. 110.  74.  53.
  34.  95.  93. 100. 127. 117. 108.  11.  21.  46. 107.  27. 106.  22.
  60. 112. 115.  54.  39. 145. 139. 137. 126.  19. 111. 134.  14.  36.
  23.  37.  31.  26. 118.]

Número de valores NaN (faltantes) en la columna 'AvgSessionMinutes' ANTES de rellenar: 12
Mediana calculada para 'AvgSessionMinutes': 76.0

Valores distintos en 'AvgSessionMinutes' DESPUÉS de rellenar NaN:
[ 87. 113.  67.  48.  90.  32.  25.  66.  70.  72. 109.  76. 138. 119.
 151.  71.  57. 123. 102.  44. 420. 101.  59. 116.  63. 103.  69.  99.
 105.  94.  51.  55.  45. 122. 510.  10. 124. 114.  85.  86.  88.  77.
  47.  92.  41.  43.  15.  78.  58.  65.  75.  96.  38.  61.  89.  50.
  98.  84.  33.  40.  73.  83.  49.  80. 104. 120.  81. 600.  64.  97.
  56.  68.  62.  30. 125. 154.  91.  79.  82.  52. 110.  74.  53.  34.
  95.  93. 100. 127. 117. 108.  11.  21.  46. 107.  27. 106.  22.  60.
 112. 115.  54.  39. 145. 139. 137. 126.  19. 111. 134.  14.  36.  23.
  37.  31.  26. 118.]

Número de valores NaN (faltantes) en la columna 'AvgSessionMinutes' DESPUÉS de rellenar: 0
Todos los valores NaN en 'AvgSessionMinutes' han sido rellenados con éxito.

Conteo de valores por cada AvgSessionMinutes (incluyendo NaN después de rellenar):
AvgSessionMinutes
76.0     19
68.0     15
75.0     13
66.0     13
74.0     12
         ..
23.0      1
37.0      1
31.0      1
26.0      1
118.0     1
Name: count, Length: 116, dtype: int64

In [22]:
print("Valores distintos en 'DaysSinceLastLogin':")
print(df['DaysSinceLastLogin'].unique())

num_nan_days_since_last_login = df['DaysSinceLastLogin'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'DaysSinceLastLogin': {num_nan_days_since_last_login}")

if num_nan_days_since_last_login > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'DaysSinceLastLogin'.")

print("\nConteo de valores por cada DaysSinceLastLogin (incluyendo NaN):")
print(df['DaysSinceLastLogin'].value_counts(dropna=False))

Valores distintos en 'DaysSinceLastLogin':
[11  0  3  9 15 10  6 13 16  1  5  7 14  8  2 22 21  4 23 12 26 17 18 19
 20 25 24]

Número de valores NaN (faltantes) en la columna 'DaysSinceLastLogin': 0

Conteo de valores por cada DaysSinceLastLogin (incluyendo NaN):
DaysSinceLastLogin
0     97
10    38
9     36
6     34
5     32
7     32
11    31
3     29
8     28
12    24
4     23
13    21
1     19
14    18
15    15
2     15
16    12
17    12
18     8
22     6
21     6
20     4
19     4
23     2
25     2
26     1
24     1
Name: count, dtype: int64

In [23]:
print("Valores distintos en 'PlayerLevel':")
print(df['PlayerLevel'].unique())

num_nan_player_level = df['PlayerLevel'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'PlayerLevel': {num_nan_player_level}")

if num_nan_player_level > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'PlayerLevel'.")
else:
    print("No se encontraron valores NaN en la columna 'PlayerLevel'.")

print("\nConteo de valores por cada nivel de jugador (incluyendo NaN):")
print(df['PlayerLevel'].value_counts(dropna=False))

Valores distintos en 'PlayerLevel':
[59 45 68 40 51 33 41 30  1  9 36 46 31 32 47 48 54 27 50 39 26 14 43 42
 61 24 71 35  5 15 29 16 37 49 67 17 44 38 10 58  7 79 62 52 20 63 22 57
 60 23 11 73  4 76 56 28 19 21  2 25 55 13 69 66 34 65 86 74  8 53  6 18
 12 72 70]

Número de valores NaN (faltantes) en la columna 'PlayerLevel': 0
No se encontraron valores NaN en la columna 'PlayerLevel'.

Conteo de valores por cada nivel de jugador (incluyendo NaN):
PlayerLevel
1     19
38    18
40    16
35    16
37    16
      ..
57     1
65     1
74     1
72     1
70     1
Name: count, Length: 75, dtype: int64

In [24]:
print("Valores distintos en 'MatchesPlayedLast30D':")
print(df['MatchesPlayedLast30D'].unique())

num_nan_matches_played = df['MatchesPlayedLast30D'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'MatchesPlayedLast30D': {num_nan_matches_played}")

if num_nan_matches_played > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'MatchesPlayedLast30D'.")
else:
    print("No se encontraron valores NaN en la columna 'MatchesPlayedLast30D'.")

print("\nConteo de valores por cada 'MatchesPlayedLast30D' (incluyendo NaN):")
print(df['MatchesPlayedLast30D'].value_counts(dropna=False))

Valores distintos en 'MatchesPlayedLast30D':
[14 24 27 39 15 35 50 40 13 33 20 46  6 25 32 21 56 17  9 22 23 26  1 28
  0 38 29 52 18  5 63 19 37 47  7 44 10  4 58 41 45 53 34  8 30 12 43 31
 62 42 16 11  3 51 36 64 54 48 61  2 68 55 69 57]

Número de valores NaN (faltantes) en la columna 'MatchesPlayedLast30D': 0
No se encontraron valores NaN en la columna 'MatchesPlayedLast30D'.

Conteo de valores por cada 'MatchesPlayedLast30D' (incluyendo NaN):
MatchesPlayedLast30D
0     24
33    18
26    18
25    17
28    17
      ..
63     1
62     1
61     1
68     1
69     1
Name: count, Length: 64, dtype: int64

In [26]:
print("Valores distintos en 'WinRate' antes de rellenar NaN:")
print(df['WinRate'].unique())

num_nan_win_rate_before = df['WinRate'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'WinRate' ANTES de rellenar: {num_nan_win_rate_before}")

# Calcular la media de WinRate
mean_win_rate = df['WinRate'].mean()
print(f"Media calculada para 'WinRate': {mean_win_rate:.3f}")

# Rellenar los valores NaN con la media
df.loc[:, 'WinRate'] = df['WinRate'].fillna(mean_win_rate)

print("\nValores distintos en 'WinRate' DESPUÉS de rellenar NaN:")
print(df['WinRate'].unique())

num_nan_win_rate_after = df['WinRate'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'WinRate' DESPUÉS de rellenar: {num_nan_win_rate_after}")

if num_nan_win_rate_after == 0:
    print("Todos los valores NaN en 'WinRate' han sido rellenados con éxito.")

print("\nConteo de valores por cada 'WinRate' (incluyendo NaN después de rellenar):")
print(df['WinRate'].value_counts(dropna=False))

Valores distintos en 'WinRate' antes de rellenar NaN:
[0.481 0.475 0.341 0.225 0.454 0.61  0.422 0.303 0.711 0.796 0.638 0.51
 0.679 0.21  0.509 0.617 0.707 0.399 0.532 0.45  0.378 0.579 0.588 0.424
 0.619   nan 0.736 0.493 0.779 0.738 0.48  0.507 0.733 0.691 0.56  0.643
 0.506 0.508 0.826 0.427 0.585 0.62  0.409 0.831 0.841 0.433 0.783 0.413
 0.542 0.496 0.919 0.384 0.657 0.55  0.608 0.587 0.242 0.416 0.592 0.891
 0.198 0.4   0.376 0.42  0.95  0.802 0.52  0.572 0.368 0.439 0.662 0.361
 0.641 0.487 0.827 0.68  0.593 0.535 0.308 0.769 0.501 0.411 0.613 0.604
 0.661 0.669 0.557 0.264 0.477 0.455 0.546 0.5   0.47  0.524 0.392 0.548
 0.467 0.544 0.632 0.469 0.528 0.734 0.497 0.462 0.624 0.541 0.502 0.369
 0.589 0.663 0.261 0.474 0.458 0.495 0.714 0.511 0.397 0.672 0.332 0.568
 0.349 0.438 0.666 0.712 0.442 0.596 0.595 0.516 0.281 0.649 0.419 0.377
 0.543 0.396 0.425 0.484 0.277 0.226 0.536 0.284 0.525 0.37  0.551 0.457
 0.407 0.386 0.618 0.494 0.584 0.443 0.446 0.257 0.263 0.421 0.301 0.697
 0.569 0.379 0.644 0.545 0.708 0.464 0.459 0.577 0.699 0.718 0.212 0.69
 0.167 0.34  0.565 0.758 0.598 0.554 0.654 0.547 0.505 0.694 0.324 0.703
 0.575 0.232 0.388 0.756 0.567 0.581 0.65  0.573 0.49  0.197 0.471 0.762
 0.193 0.512 0.53  0.372 0.561 0.441 0.352 0.468 0.327 0.415 0.698 0.562
 0.517 0.398 0.659 0.597 0.915 0.461 0.268 0.533 0.426 0.164 0.485 0.279
 0.563 0.299 0.348 0.576 0.491 0.126 0.35  0.476 0.354 0.123 0.677 0.463
 0.622 0.363 0.521 0.394 0.552 0.138 0.43  0.531 0.2   0.306 0.165 0.676
 0.78  0.743 0.75  0.298 0.408 0.582 0.875 0.629 0.571 0.527 0.682 0.77
 0.177 0.79  0.405 0.351 0.336 0.728 0.184 0.23  0.229 0.526 0.642 0.515
 0.64  0.224 0.72  0.586 0.465 0.375 0.401 0.627 0.626 0.603 0.404 0.357
 0.323 0.233 0.692 0.452 0.591 0.449 0.693 0.488 0.578 0.553 0.63  0.656
 0.794 0.479 0.636 0.646 0.805 0.132 0.866 0.775 0.33  0.683 0.22  0.514
 0.437 0.172 0.778 0.456 0.673 0.402 0.594 0.665 0.609 0.559 0.239 0.653
 0.432 0.924 0.218 0.444 0.345 0.297 0.616 0.313 0.365 0.41  0.448 0.466
 0.153 0.601 0.362 0.335 0.374 0.478 0.645 0.429 0.519 0.558 0.631 0.686
 0.717 0.451 0.695 0.668 0.414 0.621 0.423 0.486 0.723 0.309 0.513 0.674
 0.343 0.675 0.658 0.381 0.713 0.564 0.129 0.236 0.539]

Número de valores NaN (faltantes) en la columna 'WinRate' ANTES de rellenar: 12
Media calculada para 'WinRate': 0.512

Valores distintos en 'WinRate' DESPUÉS de rellenar NaN:
[0.481      0.475      0.341      0.225      0.454      0.61
 0.422      0.303      0.711      0.796      0.638      0.51
 0.679      0.21       0.509      0.617      0.707      0.399
 0.532      0.45       0.378      0.579      0.588      0.424
 0.619      0.51248327 0.736      0.493      0.779      0.738
 0.48       0.507      0.733      0.691      0.56       0.643
 0.506      0.508      0.826      0.427      0.585      0.62
 0.409      0.831      0.841      0.433      0.783      0.413
 0.542      0.496      0.919      0.384      0.657      0.55
 0.608      0.587      0.242      0.416      0.592      0.891
 0.198      0.4        0.376      0.42       0.95       0.802
 0.52       0.572      0.368      0.439      0.662      0.361
 0.641      0.487      0.827      0.68       0.593      0.535
 0.308      0.769      0.501      0.411      0.613      0.604
 0.661      0.669      0.557      0.264      0.477      0.455
 0.546      0.5        0.47       0.524      0.392      0.548
 0.467      0.544      0.632      0.469      0.528      0.734
 0.497      0.462      0.624      0.541      0.502      0.369
 0.589      0.663      0.261      0.474      0.458      0.495
 0.714      0.511      0.397      0.672      0.332      0.568
 0.349      0.438      0.666      0.712      0.442      0.596
 0.595      0.516      0.281      0.649      0.419      0.377
 0.543      0.396      0.425      0.484      0.277      0.226
 0.536      0.284      0.525      0.37       0.551      0.457
 0.407      0.386      0.618      0.494      0.584      0.443
 0.446      0.257      0.263      0.421      0.301      0.697
 0.569      0.379      0.644      0.545      0.708      0.464
 0.459      0.577      0.699      0.718      0.212      0.69
 0.167      0.34       0.565      0.758      0.598      0.554
 0.654      0.547      0.505      0.694      0.324      0.703
 0.575      0.232      0.388      0.756      0.567      0.581
 0.65       0.573      0.49       0.197      0.471      0.762
 0.193      0.512      0.53       0.372      0.561      0.441
 0.352      0.468      0.327      0.415      0.698      0.562
 0.517      0.398      0.659      0.597      0.915      0.461
 0.268      0.533      0.426      0.164      0.485      0.279
 0.563      0.299      0.348      0.576      0.491      0.126
 0.35       0.476      0.354      0.123      0.677      0.463
 0.622      0.363      0.521      0.394      0.552      0.138
 0.43       0.531      0.2        0.306      0.165      0.676
 0.78       0.743      0.75       0.298      0.408      0.582
 0.875      0.629      0.571      0.527      0.682      0.77
 0.177      0.79       0.405      0.351      0.336      0.728
 0.184      0.23       0.229      0.526      0.642      0.515
 0.64       0.224      0.72       0.586      0.465      0.375
 0.401      0.627      0.626      0.603      0.404      0.357
 0.323      0.233      0.692      0.452      0.591      0.449
 0.693      0.488      0.578      0.553      0.63       0.656
 0.794      0.479      0.636      0.646      0.805      0.132
 0.866      0.775      0.33       0.683      0.22       0.514
 0.437      0.172      0.778      0.456      0.673      0.402
 0.594      0.665      0.609      0.559      0.239      0.653
 0.432      0.924      0.218      0.444      0.345      0.297
 0.616      0.313      0.365      0.41       0.448      0.466
 0.153      0.601      0.362      0.335      0.374      0.478
 0.645      0.429      0.519      0.558      0.631      0.686
 0.717      0.451      0.695      0.668      0.414      0.621
 0.423      0.486      0.723      0.309      0.513      0.674
 0.343      0.675      0.658      0.381      0.713      0.564
 0.129      0.236      0.539     ]

Número de valores NaN (faltantes) en la columna 'WinRate' DESPUÉS de rellenar: 0
Todos los valores NaN en 'WinRate' han sido rellenados con éxito.

Conteo de valores por cada 'WinRate' (incluyendo NaN después de rellenar):
WinRate
0.512483    12
0.548000     4
0.508000     4
0.588000     4
0.680000     4
            ..
0.796000     1
0.374000     1
0.335000     1
0.362000     1
0.601000     1
Name: count, Length: 357, dtype: int64

In [27]:
print("Valores distintos en 'FriendsInGame' antes de rellenar NaN:")
print(df['FriendsInGame'].unique())

num_nan_friends_in_game_before = df['FriendsInGame'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'FriendsInGame' ANTES de rellenar: {num_nan_friends_in_game_before}")

if num_nan_friends_in_game_before > 0:
    # Calcular la media de FriendsInGame
    mean_friends_in_game = df['FriendsInGame'].mean()
    print(f"Media calculada para 'FriendsInGame': {mean_friends_in_game:.2f}")

    # Rellenar los valores NaN con la media
    df.loc[:, 'FriendsInGame'] = df['FriendsInGame'].fillna(mean_friends_in_game)

    print("\nValores distintos en 'FriendsInGame' DESPUÉS de rellenar NaN:")
    print(df['FriendsInGame'].unique())

    num_nan_friends_in_game_after = df['FriendsInGame'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'FriendsInGame' DESPUÉS de rellenar: {num_nan_friends_in_game_after}")

    if num_nan_friends_in_game_after == 0:
        print("Todos los valores NaN en 'FriendsInGame' han sido rellenados con éxito.")
else:
    print("No se encontraron valores NaN en la columna 'FriendsInGame'.")

print("\nConteo de valores por cada 'FriendsInGame' (incluyendo NaN después de rellenar si aplica):")
print(df['FriendsInGame'].value_counts(dropna=False))

Valores distintos en 'FriendsInGame' antes de rellenar NaN:
[ 3.  8.  6. nan  0.  4.  1. 18. 10.  7.  5. 19.  9. 13. 14. 12. 16. 11.
  2. 15. 20. 25. 17. 21.]

Número de valores NaN (faltantes) en la columna 'FriendsInGame' ANTES de rellenar: 12
Media calculada para 'FriendsInGame': 7.59

Valores distintos en 'FriendsInGame' DESPUÉS de rellenar NaN:
[ 3.          8.          6.          7.58921933  0.          4.
  1.         18.         10.          7.          5.         19.
  9.         13.         14.         12.         16.         11.
  2.         15.         20.         25.         17.         21.        ]

Número de valores NaN (faltantes) en la columna 'FriendsInGame' DESPUÉS de rellenar: 0
Todos los valores NaN en 'FriendsInGame' han sido rellenados con éxito.

Conteo de valores por cada 'FriendsInGame' (incluyendo NaN después de rellenar si aplica):
FriendsInGame
7.000000     46
8.000000     45
6.000000     44
0.000000     43
9.000000     43
5.000000     41
10.000000    38
11.000000    30
3.000000     29
13.000000    29
2.000000     27
4.000000     24
12.000000    20
1.000000     19
14.000000    18
7.589219     12
15.000000    12
16.000000    11
18.000000     8
19.000000     4
17.000000     4
20.000000     1
25.000000     1
21.000000     1
Name: count, dtype: int64

In [28]:
print("Valores distintos en 'UsesVoiceChat':")
print(df['UsesVoiceChat'].unique())

num_nan_uses_voice_chat = df['UsesVoiceChat'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'UsesVoiceChat': {num_nan_uses_voice_chat}")

if num_nan_uses_voice_chat > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'UsesVoiceChat'.")

    # Calcular la proporción de 0s y 1s en los datos existentes
    value_counts = df['UsesVoiceChat'].dropna().value_counts(normalize=True)
    prob_0 = value_counts.get(0, 0) # Probability of 0
    prob_1 = value_counts.get(1, 0) # Probability of 1

    print(f"\nProporción de 0s (no usa chat de voz): {prob_0:.2f}")
    print(f"Proporción de 1s (usa chat de voz): {prob_1:.2f}")

    # Rellenar los valores NaN probabilísticamente
    # Crear una serie de valores aleatorios (0 o 1) basados en las proporciones
    import numpy as np
    fill_values = np.random.choice([0, 1], size=num_nan_uses_voice_chat, p=[prob_0, prob_1])

    # Obtener los índices de los valores NaN
    nan_indices = df[df['UsesVoiceChat'].isnull()].index

    # Asignar los valores rellenados a los NaN
    df.loc[nan_indices, 'UsesVoiceChat'] = fill_values

    print("\nValores distintos en 'UsesVoiceChat' DESPUÉS de rellenar NaN:")
    print(df['UsesVoiceChat'].unique())

    num_nan_uses_voice_chat_after = df['UsesVoiceChat'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'UsesVoiceChat' DESPUÉS de rellenar: {num_nan_uses_voice_chat_after}")

    if num_nan_uses_voice_chat_after == 0:
        print("Todos los valores NaN en 'UsesVoiceChat' han sido rellenados con éxito.")
else:
    print("No se encontraron valores NaN en la columna 'UsesVoiceChat'.")

print("\nConteo de valores por cada 'UsesVoiceChat' (incluyendo NaN después de rellenar si aplica):")
print(df['UsesVoiceChat'].value_counts(dropna=False))

Valores distintos en 'UsesVoiceChat':
[1 0]

Número de valores NaN (faltantes) en la columna 'UsesVoiceChat': 0
No se encontraron valores NaN en la columna 'UsesVoiceChat'.

Conteo de valores por cada 'UsesVoiceChat' (incluyendo NaN después de rellenar si aplica):
UsesVoiceChat
1    300
0    250
Name: count, dtype: int64

In [29]:
print("Valores distintos en 'AchievementsUnlocked' antes de rellenar NaN:")
print(df['AchievementsUnlocked'].unique())

num_nan_achievements_unlocked_before = df['AchievementsUnlocked'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'AchievementsUnlocked' ANTES de rellenar: {num_nan_achievements_unlocked_before}")

if num_nan_achievements_unlocked_before > 0:
    # Calcular la media de AchievementsUnlocked
    mean_achievements_unlocked = df['AchievementsUnlocked'].mean()
    print(f"Media calculada para 'AchievementsUnlocked': {mean_achievements_unlocked:.2f}")

    # Rellenar los valores NaN con la media
    df.loc[:, 'AchievementsUnlocked'] = df['AchievementsUnlocked'].fillna(mean_achievements_unlocked)

    print("\nValores distintos en 'AchievementsUnlocked' DESPUÉS de rellenar NaN:")
    print(df['AchievementsUnlocked'].unique())

    num_nan_achievements_unlocked_after = df['AchievementsUnlocked'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'AchievementsUnlocked' DESPUÉS de rellenar: {num_nan_achievements_unlocked_after}")

    if num_nan_achievements_unlocked_after == 0:
        print("Todos los valores NaN en 'AchievementsUnlocked' han sido rellenados con éxito.")
else:
    print("No se encontraron valores NaN en la columna 'AchievementsUnlocked'.")

print("\nConteo de valores por cada 'AchievementsUnlocked' (incluyendo NaN después de rellenar si aplica):")
print(df['AchievementsUnlocked'].value_counts(dropna=False))

Valores distintos en 'AchievementsUnlocked' antes de rellenar NaN:
[17 21 26 41 35 25 16  9 36 15 30 32 28 23 44  2 14 31 24 38 61  5 18 43
  4 53  7 40 33 10 20 13  8  0 34  6 22 12 19 46  3 49 48 27 29 11 37 39
 42 45  1 50 47]

Número de valores NaN (faltantes) en la columna 'AchievementsUnlocked' ANTES de rellenar: 0
No se encontraron valores NaN en la columna 'AchievementsUnlocked'.

Conteo de valores por cada 'AchievementsUnlocked' (incluyendo NaN después de rellenar si aplica):
AchievementsUnlocked
17    21
21    21
0     21
24    20
15    20
16    19
23    19
22    19
28    18
34    18
18    18
27    18
20    16
26    15
30    15
14    14
31    14
33    13
29    13
25    13
35    12
11    12
12    12
10    11
41    11
9     11
36    10
13    10
19     9
32     8
4      8
40     8
2      8
7      8
5      7
38     7
37     7
8      7
1      5
43     4
44     4
39     4
42     3
6      3
53     3
46     3
3      3
47     2
61     1
49     1
48     1
45     1
50     1
Name: count, dtype: int64

In [30]:
print("Valores distintos en 'ReportsReceivedLast30D' antes de rellenar NaN:")
print(df['ReportsReceivedLast30D'].unique())

num_nan_reports_received_before = df['ReportsReceivedLast30D'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' ANTES de rellenar: {num_nan_reports_received_before}")

if num_nan_reports_received_before > 0:
    # Calcular la media de ReportsReceivedLast30D
    mean_reports_received = df['ReportsReceivedLast30D'].mean()
    print(f"Media calculada para 'ReportsReceivedLast30D': {mean_reports_received:.2f}")

    # Rellenar los valores NaN con la media
    df.loc[:, 'ReportsReceivedLast30D'] = df['ReportsReceivedLast30D'].fillna(mean_reports_received)

    print("\nValores distintos en 'ReportsReceivedLast30D' DESPUÉS de rellenar NaN:")
    print(df['ReportsReceivedLast30D'].unique())

    num_nan_reports_received_after = df['ReportsReceivedLast30D'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' DESPUÉS de rellenar: {num_nan_reports_received_after}")

    if num_nan_reports_received_after == 0:
        print("Todos los valores NaN en 'ReportsReceivedLast30D' han sido rellenados con éxito.")
else:
    print("No se encontraron valores NaN en la columna 'ReportsReceivedLast30D'.")

print("\nConteo de valores por cada 'ReportsReceivedLast30D' (incluyendo NaN después de rellenar si aplica):")
print(df['ReportsReceivedLast30D'].value_counts(dropna=False))

Valores distintos en 'ReportsReceivedLast30D' antes de rellenar NaN:
[0 2 1 5 3 4]

Número de valores NaN (faltantes) en la columna 'ReportsReceivedLast30D' ANTES de rellenar: 0
No se encontraron valores NaN en la columna 'ReportsReceivedLast30D'.

Conteo de valores por cada 'ReportsReceivedLast30D' (incluyendo NaN después de rellenar si aplica):
ReportsReceivedLast30D
1    200
0    192
2    107
3     31
4     15
5      5
Name: count, dtype: int64

In [31]:
print("Valores distintos en 'Churn30D':")
print(df['Churn30D'].unique())

num_nan_churn30d = df['Churn30D'].isnull().sum()
print(f"\nNúmero de valores NaN (faltantes) en la columna 'Churn30D': {num_nan_churn30d}")

if num_nan_churn30d > 0:
    print("Estos valores 'nan' representan datos faltantes en la columna 'Churn30D'.")

    # Calcular la proporción de 0s y 1s en los datos existentes
    value_counts = df['Churn30D'].dropna().value_counts(normalize=True)
    prob_0 = value_counts.get(0, 0) # Probability of 0
    prob_1 = value_counts.get(1, 0) # Probability of 1

    print(f"\nProporción de 0s (no churn): {prob_0:.2f}")
    print(f"Proporción de 1s (churn): {prob_1:.2f}")

    # Rellenar los valores NaN probabilísticamente
    import numpy as np
    fill_values = np.random.choice([0, 1], size=num_nan_churn30d, p=[prob_0, prob_1])

    # Obtener los índices de los valores NaN
    nan_indices = df[df['Churn30D'].isnull()].index

    # Asignar los valores rellenados a los NaN
    df.loc[nan_indices, 'Churn30D'] = fill_values

    print("\nValores distintos en 'Churn30D' DESPUÉS de rellenar NaN:")
    print(df['Churn30D'].unique())

    num_nan_churn30d_after = df['Churn30D'].isnull().sum()
    print(f"\nNúmero de valores NaN (faltantes) en la columna 'Churn30D' DESPUÉS de rellenar: {num_nan_churn30d_after}")

    if num_nan_churn30d_after == 0:
        print("Todos los valores NaN en 'Churn30D' han sido rellenados con éxito.")
else:
    print("No se encontraron valores NaN en la columna 'Churn30D'.")

print("\nConteo de valores por cada 'Churn30D' (incluyendo NaN después de rellenar si aplica):")
print(df['Churn30D'].value_counts(dropna=False))

Valores distintos en 'Churn30D':
[0 1]

Número de valores NaN (faltantes) en la columna 'Churn30D': 0
No se encontraron valores NaN en la columna 'Churn30D'.

Conteo de valores por cada 'Churn30D' (incluyendo NaN después de rellenar si aplica):
Churn30D
0    324
1    226
Name: count, dtype: int64